"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarClock, Check, HandCoins, History, Plus, RefreshCw } from "lucide-react";
import { SectionHeader } from "@/components/ui/section-header";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Drawer } from "@/components/ui/drawer";
import { allocateDebtPayment, decimalMoneyToCents, generateDebtPlan, projectDebtPortfolio, type DebtAccess, type DebtPaymentAllocation, type DebtPlan } from "@/lib/debts/plans";
import { cancelDebtPlanRecordAction, createDebtPlanAction, editDebtPlanAction, getDebtOperationResultAction, registerDebtPlanPaymentAction, registerLegacyDebtPaymentAction, verifyDebtSessionAction, voidDebtPlanPaymentAction } from "@/app/actions/debt-plans";
import { CREDITOR_TYPES, DEBT_CATEGORIES, debtErrorMessage, parseCancelPlanRequest, parseCreatePlanRequest, parseEditPlanRequest, parsePaymentPlanRequest, parseVoidPlanRequest, type CancelPlanRequest, type ExpectedDebtSession, type CreatePlanRequest, type EditPlanRequest, type PaymentPlanRequest, type VoidPlanRequest } from "./plan-contract";
import { storedMoney, type DebtView } from "./plan-data";
import { parseOperationJournal, serializeOperationJournal, retainDebtOperation, clearDebtOperation, operationReference, type DebtOperationJournal, type DebtOperationReference, type PendingDebtOperation } from "./operation-journal";
import { summarizeDebtViews } from "./portfolio-summary";
type RecoveryProps = { expectedSession: ExpectedDebtSession; onSessionMismatch: () => void; pending?: PendingDebtOperation; onRetain: (operation: PendingDebtOperation) => boolean; onClear: (requestId: string) => void };

async function lookupOperation(entry: DebtOperationReference, expectedSession: ExpectedDebtSession) {
  const operation = entry.kind === "edit" ? entry.targetId ? "edit_installment" : "edit_notes" : entry.kind;
  try { return await getDebtOperationResultAction({ operation, requestId: entry.requestId, ...(entry.debtId ? { debtId: entry.debtId } : {}) }, expectedSession); }
  catch { return { ok: false as const, error: "No pudimos verificar el resultado. Conservamos el mismo identificador; no generes otro para repetir esta operación." }; }
}

const inputClass = "w-full rounded-lg border border-line bg-bg-subtle px-3 py-2 text-sm text-ink focus:outline-none focus:ring-2 focus:ring-brand-500/40 disabled:opacity-60";
const statusLabels: Record<string, string> = { pending: "Pendiente", in_plan: "En plan", partially_paid: "Parcialmente pagada", paid: "Pagada", overdue: "Vencida", partial: "Parcial", active: "Activa", settled: "Saldada", cancelled: "Cancelada" };
const originLabels: Record<string, string> = { manual: "Manual", whatsapp: "WhatsApp", purchase: "Compra", invoice: "Factura", api: "API", system: "Sistema" };
const ratePeriods: Record<string, string> = { weekly: "Semanal", fortnightly: "Quincenal", monthly: "Mensual", annual: "Anual", one_time: "Única", unspecified: "No especificada" };
function money(cents: number, currency: string | null) { return `${currency ?? "Moneda no confirmada"} ${new Intl.NumberFormat("es-AR", { maximumFractionDigits: 0 }).format(Math.floor(cents / 100))},${String(cents % 100).padStart(2, "0")}`; }
function date(value: string | null) { return value ? value.slice(0, 10).split("-").reverse().join("/") : "Sin fecha"; }
function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="block space-y-1.5 text-xs font-medium text-ink-muted"><span>{label}</span>{children}{hint && <span className="block text-[11px] font-normal">{hint}</span>}</label>; }
function ErrorMessage({ error }: { error: string }) { return error ? <p role="alert" className="rounded-lg border border-danger-500/30 bg-danger-500/10 p-3 text-sm text-danger-300">{error}</p> : null; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-line bg-bg-subtle p-3"><p className="text-xs text-ink-muted">{label}</p><p className="mt-1 font-semibold text-ink">{value}</p></div>; }

export default function DatabaseDebtsClient({ debts, branches, access, asOfDate, timeZone }: { debts: DebtView[]; branches: { id: string; name: string }[]; access: DebtAccess; asOfDate: string; timeZone: string }) {
  const router = useRouter();
  const [branch, setBranch] = useState("");
  const [currency, setCurrency] = useState("");
  const [status, setStatus] = useState("");
  const [search, setSearch] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [paymentId, setPaymentId] = useState<string | null>(null);
  const [paymentOpen, setPaymentOpen] = useState(false);
  // Retain each draft/operation identity when another debt or payment is opened.
  const [paymentDraftIds, setPaymentDraftIds] = useState<string[]>([]);
  const [voidDrafts, setVoidDrafts] = useState<{ debtId: string; paymentId: string }[]>([]);
  const [activeVoid, setActiveVoid] = useState<string | null>(null);
  const [editDrafts, setEditDrafts] = useState<{ debtId: string; installmentId: string | null }[]>([]);
  const [activeEdit, setActiveEdit] = useState<string | null>(null);
  const [notice, setNotice] = useState("");
  const selected = debts.find((debt) => debt.id === selectedId) ?? null;
  const [journalState, setJournal] = useState<DebtOperationJournal>({ active: [], expired: [] });
  const journal = journalState.active;
  const expired = journalState.expired;
  const journalRef = useRef<DebtOperationJournal>({ active: [], expired: [] });
  const [journalReady, setJournalReady] = useState(false);
  const [journalError, setJournalError] = useState("");
  const journalKey = `debt-operations:v1:${access.businessId}:${access.actorId}`;
  useEffect(() => {
    try { const entries = parseOperationJournal(sessionStorage.getItem(journalKey)); sessionStorage.setItem(journalKey, serializeOperationJournal(entries)); journalRef.current = entries; setJournal(entries); setJournalReady(true); }
    catch { setJournalError("No pudimos recuperar los intentos pendientes de esta pestaña. Revisá el historial antes de iniciar nuevos registros; las acciones están bloqueadas para evitar duplicados."); return; }
    const timer = window.setInterval(() => {
      try { const raw = serializeOperationJournal(journalRef.current); const entries = parseOperationJournal(raw); sessionStorage.setItem(journalKey, raw); journalRef.current = entries; setJournal(entries); }
      catch { setJournalError("No pudimos verificar la recuperación de esta pestaña. Las acciones nuevas están bloqueadas hasta revisar el historial."); }
    }, 60_000);
    return () => window.clearInterval(timer);
  }, [journalKey]);
  function retain(operation: PendingDebtOperation): boolean {
    try { const entries = retainDebtOperation(journalRef.current, operation); sessionStorage.setItem(journalKey, serializeOperationJournal(entries)); journalRef.current = entries; setJournal(entries); return true; }
    catch { setJournalError("No pudimos conservar el identificador de recuperación. No se enviaron nuevos cambios. Verificá que el navegador permita almacenamiento para esta aplicación."); return false; }
  }
  function clear(requestId: string) {
    try { const entries = clearDebtOperation(journalRef.current, requestId); sessionStorage.setItem(journalKey, serializeOperationJournal(entries)); journalRef.current = entries; setJournal(entries); }
    catch { setJournalError("El resultado se recibió, pero no pudimos limpiar el intento guardado. Si reaparece al recargar, comprobalo usando el mismo identificador."); }
  }
  const [sessionMismatch, setSessionMismatch] = useState(false);
  const expectedSession = { actorId: access.actorId, businessId: access.businessId };
  function onSessionMismatch() { setSessionMismatch(true); router.refresh(); }
  useEffect(() => {
    let live = true;
    const check = () => { void verifyDebtSessionAction(null, { actorId: access.actorId, businessId: access.businessId }).then((result) => {
      if (live && result.ok) setSessionMismatch(false);
      if (live && !result.ok && ["session_changed", "no_session", "permission_denied"].includes(result.code)) { setSessionMismatch(true); router.refresh(); }
    }).catch(() => { /* Server mutation fences remain authoritative during offline reads. */ }); };
    const visible = () => { if (document.visibilityState === "visible") check(); };
    window.addEventListener("focus", check); document.addEventListener("visibilitychange", visible); check();
    return () => { live = false; window.removeEventListener("focus", check); document.removeEventListener("visibilitychange", visible); };
  }, [access.actorId, access.businessId, router]);
  const recovery = { expectedSession, onSessionMismatch, onRetain: retain, onClear: clear };
  const [legacyMatches, setLegacyMatches] = useState<Record<string, string>>({});
  const [checking, setChecking] = useState<string | null>(null);
  async function verifyExpired(entry: DebtOperationReference) {
    if (checking) return;
    setChecking(entry.requestId);
    try {
      if (entry.kind === "legacy") { setNotice("Este pago histórico no tiene un identificador consultable en el servidor. El resultado sigue pendiente: revisá su historial y conservá esta referencia antes de registrar otro pago."); return; }
      const result = await lookupOperation(entry, expectedSession);
      if (result.ok && result.found) { clear(entry.requestId); setNotice("El servidor confirmó la operación pendiente. Su identificador quedó reconciliado."); router.refresh(); }
      else { if (!result.ok && "code" in result && ["session_changed", "no_session"].includes(String(result.code))) onSessionMismatch(); setNotice(result.ok ? "Todavía no encontramos un resultado confirmado. Esto no demuestra que haya fallado: conservamos la referencia y bloqueamos otro registro de esta operación." : result.error); }
    } finally { setChecking(null); }
  }
  const allPaymentDraftIds = [...new Set([...paymentDraftIds, ...journal.flatMap((entry) => entry.kind === "pay" || entry.kind === "legacy" ? [entry.request.debtId] : [])])];
  const allVoidDrafts = [...voidDrafts, ...journal.flatMap((entry) => entry.kind === "void" && !voidDrafts.some((draft) => draft.paymentId === entry.request.paymentId) ? [{ debtId: entry.request.debtId, paymentId: entry.request.paymentId }] : [])];
  const [cancelDraftIds, setCancelDraftIds] = useState<string[]>([]);
  const [activeCancel, setActiveCancel] = useState<string | null>(null);
  const allCancelDraftIds = [...new Set([...cancelDraftIds, ...journal.flatMap((entry) => entry.kind === "cancel" ? [entry.request.debtId] : [])])];
  const allEditDrafts = [...editDrafts];
  for (const entry of journal) if (entry.kind === "edit") {
    const installmentId = entry.request.kind === "installment" ? entry.request.installmentId : null;
    if (!allEditDrafts.some((draft) => draft.debtId === entry.request.debtId && draft.installmentId === installmentId)) allEditDrafts.push({ debtId: entry.request.debtId, installmentId });
  }
  function openEdit(debtId: string, installmentId: string | null) {
    setEditDrafts((drafts) => drafts.some((draft) => draft.debtId === debtId && draft.installmentId === installmentId) ? drafts : [...drafts, { debtId, installmentId }]);
    setActiveEdit(`${debtId}:${installmentId ?? "notes"}`); setSelectedId(null);
  }
  const canCreate = access.permissions.includes("debts.create") && journalReady && !journalError && !expired.some((entry) => entry.kind === "create");
  const canPay = access.permissions.includes("debts.pay") && journalReady && !journalError;
  const branchName = (id: string | null) => branches.find((item) => item.id === id)?.name ?? "Sin sucursal histórica";
  const currencies = [...new Set(debts.flatMap((debt) => debt.currency ? [debt.currency] : []))].sort();
  const scoped = useMemo(() => debts.filter((debt) => (!branch || debt.branchId === branch) && (!currency || (currency === "unknown" ? debt.currency === null : debt.currency === currency))), [debts, branch, currency]);
  const filtered = useMemo(() => scoped.filter((debt) => (!status || (status === "cancelled" ? debt.status === "cancelled" : debt.status !== "cancelled" && (status === "paid" ? debt.pendingCents === 0 : status === "overdue" ? debt.status === "overdue" : debt.pendingCents > 0))) && `${debt.creditor} ${debt.concept ?? ""}`.toLowerCase().includes(search.toLowerCase())), [scoped, status, search]);
  const portfolios = useMemo(() => [...new Set(filtered.filter((debt) => debt.ledger).map((debt) => debt.currency!))].map((code) => projectDebtPortfolio(filtered.flatMap((debt) => debt.ledger ? [debt.ledger] : []), { currency: code, asOfDate }, access)), [filtered, asOfDate, access]);
  const summaries = summarizeDebtViews(filtered);
  function updated(message: string) { setNotice(message); router.refresh(); }
  if (sessionMismatch) return <div className="space-y-3 p-6"><p role="alert">La sesión cambió. Actualizando el acceso al negocio…</p><Button onClick={() => window.location.reload()}>Verificar sesión y recargar</Button></div>;
  return <div className="space-y-6">
    <SectionHeader eyebrow="Finanzas · Obligaciones" title="Deudas y planes de pago" description="Saldos, cuotas y vencimientos registrados. Los pagos son anotaciones del negocio y no realizan transferencias." />
    <div className="flex flex-wrap justify-between gap-3"><p className="text-xs text-ink-muted">Corte: {date(asOfDate)} · {timeZone}. Ventanas desde hoy, excluyen vencidos.</p><div className="flex gap-2"><Button onClick={() => router.refresh()}><RefreshCw className="h-4 w-4" />Actualizar</Button>{canCreate && <Button variant="primary" onClick={() => setCreateOpen(true)} disabled={!branches.length}><Plus className="h-4 w-4" />Nueva deuda</Button>}</div></div>
    <ErrorMessage error={journalError} />
    {journal.length > 0 && <div className="space-y-2 rounded-lg border border-line p-3 text-sm"><p>Hay intentos guardados que necesitan confirmación de resultado. Usá estos mismos intentos para evitar registros duplicados.</p>{journal.map((entry) => <Button key={entry.request.requestId} size="sm" onClick={() => { if (entry.kind === "create") setCreateOpen(true); else if (entry.kind === "cancel") setActiveCancel(entry.request.debtId); else if (entry.kind === "void") setActiveVoid(entry.request.paymentId); else if (entry.kind === "edit") openEdit(entry.request.debtId, entry.request.kind === "installment" ? entry.request.installmentId : null); else { setPaymentId(entry.request.debtId); setPaymentOpen(true); } }}>Recuperar {entry.kind === "create" ? "creación de deuda" : entry.kind === "void" ? "anulación" : entry.kind === "cancel" ? "cancelación administrativa" : entry.kind === "edit" ? "edición" : "pago"}{entry.kind !== "create" ? ` · ${debts.find((debt) => debt.id === entry.request.debtId)?.creditor ?? "Deuda no disponible"}` : ""}</Button>)}</div>}
    {expired.length > 0 && <div className="space-y-2 rounded-lg border border-line p-3 text-sm"><p>El borrador de estos intentos venció después de 24 horas en la pestaña. Conservamos sólo su referencia. El vencimiento no confirma ni cancela la operación; verificá el resultado antes de crear otro registro.</p>{expired.map((entry) => <div key={entry.requestId} className="flex flex-wrap items-center gap-2"><span className="break-all text-xs">{entry.kind} · {entry.requestId}</span><Button size="sm" disabled={!!checking} onClick={() => void verifyExpired(entry)}>{checking === entry.requestId ? "Comprobando…" : "Comprobar resultado autenticado"}</Button>{entry.kind === "legacy" && <div className="w-full space-y-2"><p className="text-xs">Si verificaste que el pago histórico se registró, elegí su registro para conciliar este intento. Esto no registra ni anula dinero.</p><select aria-label="Pago histórico verificado" className={inputClass} value={legacyMatches[entry.requestId] ?? ""} onChange={(event) => setLegacyMatches((matches) => ({ ...matches, [entry.requestId]: event.target.value }))}><option value="">Elegí el pago que comprobaste en el historial</option>{debts.find((debt) => debt.id === entry.debtId)?.payments.map((payment) => <option key={payment.id} value={payment.id}>{date(payment.paid_at)} · {payment.amount} · {payment.payment_method} · {payment.id}</option>)}</select><Button size="sm" disabled={!debts.find((debt) => debt.id === entry.debtId)?.payments.some((payment) => payment.id === legacyMatches[entry.requestId])} onClick={() => { const match = debts.find((debt) => debt.id === entry.debtId)?.payments.find((payment) => payment.id === legacyMatches[entry.requestId]); if (match) { clear(entry.requestId); setNotice("Confirmaste manualmente qué pago histórico corresponde al intento pendiente. No se creó otro pago."); } }}>Confirmar que ese pago resuelve el intento</Button></div>}</div>)}</div>}
    {notice && <p role="status" className="rounded-lg border border-success-500/30 bg-success-500/10 p-3 text-sm text-ink">{notice}</p>}
    <div className="grid gap-3 sm:grid-cols-4"><Field label="Sucursal"><select className={inputClass} value={branch} onChange={(e) => setBranch(e.target.value)}><option value="">Todas las autorizadas</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Moneda"><select className={inputClass} value={currency} onChange={(e) => setCurrency(e.target.value)}><option value="">Todas, sin sumar entre monedas</option>{currencies.map((code) => <option key={code}>{code}</option>)}<option value="unknown">Sin moneda confirmada</option></select></Field><Field label="Estado"><select className={inputClass} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos</option><option value="pending">Con saldo pendiente</option><option value="overdue">Vencidas</option><option value="paid">Pagadas</option><option value="cancelled">Canceladas administrativamente</option></select></Field><Field label="Buscar acreedor o concepto"><input className={inputClass} value={search} onChange={(e) => setSearch(e.target.value)} /></Field></div>
    {portfolios.map((portfolio) => <Card key={portfolio.currency}><CardContent className="space-y-3 pt-5"><p className="text-sm font-semibold">Compromisos confirmados · {portfolio.currency} · {portfolio.debtCount} deudas</p><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Saldo pendiente" value={money(portfolio.pendingAmountCents, portfolio.currency)} /><Stat label="Vencido" value={money(portfolio.overdueAmountCents, portfolio.currency)} /><Stat label="Próximos 7 días" value={money(portfolio.next7DaysCents, portfolio.currency)} /><Stat label="Próximos 30 días" value={money(portfolio.next30DaysCents, portfolio.currency)} /><Stat label="Próximos 60 días" value={money(portfolio.next60DaysCents, portfolio.currency)} /><Stat label="Cuotas pendientes de este mes" value={money(portfolio.dueThisMonthCents, portfolio.currency)} /><Stat label="Pagos del cronograma vigentes" value={money(portfolio.paidAmountCents, portfolio.currency)} /><Stat label="Saldo sin vencimiento" value={money(portfolio.unscheduledAmountCents, portfolio.currency)} /></div></CardContent></Card>)}
    {summaries.currencies.length > 0 && <Card><CardContent className="space-y-4 pt-5"><h2 className="font-semibold">Saldos registrados por acreedor</h2><p className="text-xs text-ink-muted">Incluye planes y saldos históricos con moneda confirmada. Respeta todos los filtros. Los históricos no aportan cuotas ni proyecciones de vencimientos. Estos saldos no se suman a gastos.</p>
      <div className="grid gap-3 sm:grid-cols-2">{summaries.currencies.map((group) => <div key={group.currency} className="rounded-lg border border-line p-3"><p className="font-semibold">Total registrado · {group.currency}: {money(group.pendingCents, group.currency)}</p><p className="text-xs text-ink-muted">Planes: {money(group.plannedPendingCents, group.currency)} · Históricos: {money(group.legacyPendingCents, group.currency)}</p></div>)}</div>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Acreedor", "Moneda", "Registros", "Saldo en planes", "Saldo histórico", "Saldo total"].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{summaries.creditors.map((group) => <tr key={JSON.stringify([group.currency, group.creditor, group.creditorType])} className="border-t border-line"><td className="p-2">{group.creditor}<p className="text-xs text-ink-muted">{CREDITOR_TYPES[group.creditorType as keyof typeof CREDITOR_TYPES] ?? "Tipo no informado"}</p></td><td className="p-2">{group.currency}</td><td className="p-2">{group.debtCount}</td><td className="p-2">{money(group.plannedPendingCents, group.currency)}</td><td className="p-2">{money(group.legacyPendingCents, group.currency)}</td><td className="p-2">{money(group.pendingCents, group.currency)}</td></tr>)}</tbody></table></div>
    </CardContent></Card>}
    {summaries.unknown.length > 0 && <Card><CardContent className="space-y-2 pt-5"><h2 className="font-semibold">Históricos sin moneda confirmada</h2><p className="text-xs text-ink-muted">Se muestran individualmente. No se supone ARS ni se suman importes cuya moneda se desconoce.</p>{summaries.unknown.map((debt) => <p key={debt.id} className="text-sm">{debt.creditor}: {money(debt.pendingCents, null)}</p>)}</CardContent></Card>}
    {summaries.cancelled.length > 0 && <p className="rounded-lg border border-line p-3 text-xs text-ink-muted">{summaries.cancelled.length} registro(s) cancelado(s) administrativamente fuera de los compromisos activos. Conservan importes e historial; la cancelación del registro no paga ni extingue la obligación con el acreedor.</p>}
    <Card><CardContent className="pt-5"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line text-xs text-ink-muted"><tr>{["Acreedor / concepto", "Saldo", "Próximo vencimiento", "Cuotas", "Estado", "Sucursal / origen", ""].map((label, i) => <th key={i} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{filtered.map((debt) => { const next = debt.projection?.installments.find((part) => part.dueDate === debt.projection?.nextDueDate && part.pendingAmountCents > 0); return <tr key={debt.id} className="border-b border-line/60"><td className="p-3"><p className="font-semibold">{debt.creditor}</p><p className="text-xs text-ink-muted">{debt.concept ?? "Sin concepto"}</p></td><td className="p-3 tabular-nums">{money(debt.pendingCents, debt.currency)}{debt.status === "cancelled" && <p className="text-xs text-ink-muted">Saldo histórico al cancelar</p>}</td><td className="p-3">{date(debt.ledger ? debt.projection?.nextDueDate ?? null : debt.dueDate)}{next && <p className="text-xs text-ink-muted">{money(next.pendingAmountCents, debt.currency)}</p>}</td><td className="p-3">{debt.projection ? `${debt.projection.paidInstallmentCount} / ${debt.projection.installmentCount} pagadas` : "Histórica"}</td><td className="p-3">{statusLabels[debt.status] ?? debt.status}</td><td className="p-3 text-xs">{branchName(debt.branchId)}<p className="text-ink-muted">{originLabels[debt.origin ?? ""] ?? "Origen no informado"}</p></td><td className="p-3"><Button size="sm" onClick={() => setSelectedId(debt.id)}>Ver detalle</Button></td></tr>; })}</tbody></table>{!filtered.length && <p className="py-12 text-center text-sm text-ink-muted">{debts.length ? "No hay deudas para estos filtros." : "Todavía no hay deudas registradas."}</p>}</div></CardContent></Card>
    <Drawer open={!!selected} onClose={() => setSelectedId(null)} title={selected?.creditor} description={selected?.concept ?? undefined} width="max-w-3xl">{selected && <DebtDetail key={selected.id} debt={selected} branchName={branchName(selected.branchId)} canPay={canPay && selected.status !== "cancelled" && !expired.some((entry) => entry.debtId === selected.id)} canEdit={canCreate && selected.status !== "cancelled" && !expired.some((entry) => entry.debtId === selected.id)} onEdit={(installmentId) => openEdit(selected.id, installmentId)} canCancel={canCreate && selected.status !== "cancelled" && !!selected.ledger && !journal.some((entry) => entry.kind !== "create" && entry.request.debtId === selected.id) && !expired.some((entry) => entry.debtId === selected.id)} onCancel={() => { setCancelDraftIds((ids) => ids.includes(selected.id) ? ids : [...ids, selected.id]); setActiveCancel(selected.id); setSelectedId(null); }} onPay={() => { setPaymentDraftIds((ids) => ids.includes(selected.id) ? ids : [...ids, selected.id]); setPaymentId(selected.id); setPaymentOpen(true); setSelectedId(null); }} onVoid={(id) => { setVoidDrafts((drafts) => drafts.some((item) => item.paymentId === id) ? drafts : [...drafts, { debtId: selected.id, paymentId: id }]); setActiveVoid(id); setSelectedId(null); }} />}</Drawer>
    {journalReady && allCancelDraftIds.filter((id) => !expired.some((entry) => entry.kind === "cancel" && entry.debtId === id)).map((id) => { const debt = debts.find((item) => item.id === id); return debt ? <CancelDebtForm {...recovery} key={id} debt={debt} pending={journal.find((entry) => entry.kind === "cancel" && entry.request.debtId === id)} open={activeCancel === id} onClose={() => setActiveCancel(null)} onSaved={() => { setActiveCancel(null); setSelectedId(id); updated("Registro cancelado administrativamente. Se conservaron el saldo y todos los pagos; no se extinguió la obligación con el acreedor."); }} /> : null; })}
    {journalReady && !expired.some((entry) => entry.kind === "create") && <NewDebtDrawer {...recovery} pending={journal.find((entry) => entry.kind === "create")} open={createOpen} onClose={() => setCreateOpen(false)} branches={branches} today={asOfDate} onSaved={() => { setCreateOpen(false); updated("Deuda y cronograma guardados. El saldo se calculó desde las cuotas reales."); }} />}
    {journalReady && allPaymentDraftIds.filter((id) => !expired.some((entry) => entry.debtId === id && (entry.kind === "pay" || entry.kind === "legacy"))).map((id) => { const paying = debts.find((debt) => debt.id === id); return paying ? <PaymentDrawer {...recovery} pending={journal.find((entry) => (entry.kind === "pay" || entry.kind === "legacy") && entry.request.debtId === paying.id)} key={paying.id} open={paymentOpen && paymentId === paying.id} onClose={() => setPaymentOpen(false)} debt={paying} access={access} today={asOfDate} onSaved={() => { setPaymentOpen(false); setSelectedId(paying.id); updated("Pago registrado en el historial. No se realizó una transferencia."); }} onRefresh={() => router.refresh()} /> : null; })}
    {journalReady && allVoidDrafts.filter((item) => !expired.some((entry) => entry.kind === "void" && entry.targetId === item.paymentId)).map((item) => { const debt = debts.find((row) => row.id === item.debtId); return debt ? <VoidPaymentForm {...recovery} pending={journal.find((entry) => entry.kind === "void" && entry.request.paymentId === item.paymentId)} key={item.paymentId} open={activeVoid === item.paymentId} debt={debt} paymentId={item.paymentId} onClose={() => setActiveVoid(null)} onSaved={() => { setActiveVoid(null); setSelectedId(debt.id); updated("Pago anulado con motivo e historial conservado. Se recalculó el saldo de las cuotas."); }} /> : null; })}
    {journalReady && allEditDrafts.filter((item) => !expired.some((entry) => entry.kind === "edit" && entry.debtId === item.debtId && entry.targetId === item.installmentId)).map((item) => { const debt = debts.find((row) => row.id === item.debtId); const key = `${item.debtId}:${item.installmentId ?? "notes"}`; return debt ? <EditDebtDrawer {...recovery} pending={journal.find((entry) => entry.kind === "edit" && entry.request.debtId === item.debtId && (entry.request.kind === "installment" ? entry.request.installmentId : null) === item.installmentId)} key={key} open={activeEdit === key} debt={debt} installmentId={item.installmentId} onClose={() => setActiveEdit(null)} onSaved={() => { setActiveEdit(null); setSelectedId(debt.id); updated("Edición guardada con auditoría. El cronograma muestra los vencimientos actuales."); }} /> : null; })}
  </div>;
}

function DebtDetail({ debt, branchName, canPay, canEdit, canCancel, onCancel, onEdit, onPay, onVoid }: { debt: DebtView; branchName: string; canPay: boolean; canEdit: boolean; canCancel: boolean; onCancel: () => void; onEdit: (installmentId: string | null) => void; onPay: () => void; onVoid: (paymentId: string) => void }) {
  return <div className="space-y-6 p-6"><div className="grid grid-cols-2 gap-3"><Stat label={debt.status === "cancelled" ? "Saldo histórico al cancelar" : "Saldo actual"} value={money(debt.pendingCents, debt.currency)} /><Stat label="Monto original" value={money(debt.originalCents, debt.currency)} /><Stat label="Fecha de origen" value={date(debt.takenAt)} /><Stat label="Estado" value={statusLabels[debt.status] ?? debt.status} />{debt.plan && <><Stat label="Total del cronograma" value={money(debt.plan.totalFinancedCents, debt.currency)} /><Stat label="Anticipo histórico confirmado" value={debt.plan.downPaymentCents === null ? "No informado" : money(debt.plan.downPaymentCents, debt.currency)} /></>}</div>
    <p className="text-sm text-ink-muted">{branchName} · {CREDITOR_TYPES[debt.creditorType as keyof typeof CREDITOR_TYPES] ?? "Tipo no informado"} · {DEBT_CATEGORIES[debt.category as keyof typeof DEBT_CATEGORIES] ?? "Sin categoría"}</p>
    {debt.plan?.interestRate && <p className="text-sm">Tasa informada: {debt.plan.interestRate.value}% · {ratePeriods[debt.plan.interestRate.period]}. No se recalcula el importe de las cuotas a partir de esta tasa.</p>}
    {debt.plan?.confirmedBalance && <p className="text-sm">Interés monetario confirmado: {money(debt.plan.confirmedBalance.interestCents, debt.currency)} · Recargos: {money(debt.plan.confirmedBalance.feesCents, debt.currency)}. El anticipo ya pagado está fuera del cronograma y no se descuenta nuevamente.</p>}
    {debt.expectedPaymentMethod && <p className="text-sm">Método previsto: {debt.expectedPaymentMethod}</p>}{debt.reference && <p className="text-sm">Referencia: {debt.reference}</p>}{debt.notes && <p className="whitespace-pre-wrap text-sm text-ink-muted">{debt.notes}</p>}
    {debt.ledger?.cancelled && <div className="space-y-1 rounded-lg border border-warning-500/30 p-3 text-sm"><p className="font-semibold">Registro cancelado administrativamente</p><p>Motivo: {debt.ledger.cancelled.reason}</p><p>Fecha: {date(debt.ledger.cancelled.cancelledAt)} · Actor: {debt.ledger.cancelled.actorId}</p><p className="text-xs">Importes, cuotas y pagos conservados como historial. Fuera de compromisos activos. Esto no acredita un pago ni extingue la obligación con el acreedor.</p></div>}
    {canCancel && <Button onClick={onCancel}>Cancelar registro administrativamente</Button>}
    {canEdit && debt.ledger && <Button onClick={() => onEdit(null)}>Editar notas de la deuda</Button>}
    {canPay && debt.pendingCents > 0 && <Button variant="primary" onClick={onPay}><HandCoins className="h-4 w-4" />Registrar pago parcial, anticipado o global</Button>}
    <section className="space-y-3"><h3 className="flex items-center gap-2 font-semibold"><CalendarClock className="h-4 w-4" />Cronograma</h3>{debt.projection ? <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{["Cuota", "Vencimiento", "Importe", "Pagado", "Saldo / estado"].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{debt.projection.installments.map((part) => { const component = debt.components.find((item) => item.id === part.id); return <tr key={part.id} className="border-t border-line"><td className="p-2">{part.installmentNumber}</td><td className="p-2">{date(part.dueDate)}{component?.notes && <p className="text-ink-muted">{component.notes}</p>}{canEdit && <Button size="sm" onClick={() => onEdit(part.id)}>Editar vencimiento / notas</Button>}</td><td className="p-2">{money(part.totalAmountCents, debt.currency)}{component && [component.capitalCents, component.interestCents, component.feesCents].some((value) => value !== null) && <p className="mt-1 text-[10px] text-ink-muted">Capital: {component.capitalCents === null ? "No informado" : money(component.capitalCents, debt.currency)} · Interés: {component.interestCents === null ? "No informado" : money(component.interestCents, debt.currency)} · Recargo: {component.feesCents === null ? "No informado" : money(component.feesCents, debt.currency)}</p>}</td><td className="p-2">{money(part.paidAmountCents, debt.currency)}</td><td className="p-2">{money(part.pendingAmountCents, debt.currency)}<p className="text-ink-muted">{statusLabels[part.status]}</p></td></tr>; })}</tbody></table></div> : <p className="text-sm text-ink-muted">Deuda histórica sin cronograma de cuotas. Vencimiento registrado: {date(debt.dueDate)}.</p>}</section>
    <section className="space-y-3"><h3 className="flex items-center gap-2 font-semibold"><History className="h-4 w-4" />Historial de pagos</h3>{debt.payments.length ? [...debt.payments].sort((a, b) => b.created_at.localeCompare(a.created_at)).map((payment) => <div key={payment.id} className="space-y-2 rounded-lg border border-line p-3 text-sm"><p className="font-semibold">{money(storedMoney(payment.amount), payment.currency ?? debt.currency)} · {date(payment.paid_at)}{payment.voided_at && " · Anulado"}</p><p>{payment.payment_method} · {originLabels[payment.origin ?? ""] ?? "Origen histórico no informado"}</p><p className="break-all text-xs text-ink-muted">Actor: {payment.created_by ?? "No disponible"} · Registro: {payment.created_at}</p>{payment.reference && <p>Referencia: {payment.reference}</p>}{payment.notes && <p className="whitespace-pre-wrap text-ink-muted">{payment.notes}</p>}{debt.ledger?.payments.find((item) => item.id === payment.id)?.allocations.map((allocation) => <p key={allocation.installmentId} className="text-xs">Cuota {debt.ledger!.installments.find((part) => part.id === allocation.installmentId)?.installmentNumber}: {money(allocation.amountCents, debt.currency)}</p>)}{payment.voided_at ? <p className="text-xs text-ink-muted">Anulado el {date(payment.voided_on)} · Actor: {payment.voided_by} · Motivo: {payment.void_reason}</p> : canPay && debt.ledger && <Button size="sm" onClick={() => onVoid(payment.id)}>Anular con motivo</Button>}</div>) : <p className="text-sm text-ink-muted">Sin pagos registrados en el cronograma.</p>}</section>
    <section className="space-y-3"><h3 className="font-semibold">Origen y auditoría</h3><p className="break-all text-xs text-ink-muted">Origen: {originLabels[debt.origin ?? ""] ?? "No informado"} · Creación: {debt.createdAt} · Actor: {debt.createdBy ?? "No disponible"} · Versión: {debt.ledger?.version ?? "Histórica"}</p>{[...debt.audit].sort((a, b) => b.created_at.localeCompare(a.created_at)).map((event) => <div key={event.id} className="border-t border-line pt-2 text-xs"><p>{event.summary}</p><p className="break-all text-ink-muted">{event.action} · {event.created_at} · {event.actor_id ?? "Actor no disponible"}</p></div>)}</section>
  </div>;
}

type NewDraft = { creditor: string; creditorType: string; concept: string; branchId: string; currency: string; takenAt: string; category: string; reference: string; notes: string; expectedPaymentMethod: string; mode: string; originalAmount: string; financingMode: string; financedAmount: string; installmentAmount: string; downPayment: string; interestAmount: string; feesAmount: string; downPaymentConfirmed: boolean; count: string; periodicity: string; dueDate: string; customDates: string; rate: string; ratePeriod: string };
function initialDraft(today: string): NewDraft { return { creditor: "", creditorType: "", concept: "", branchId: "", currency: "", takenAt: today, category: "", reference: "", notes: "", expectedPaymentMethod: "", mode: "single", originalAmount: "", financingMode: "total", financedAmount: "", installmentAmount: "", downPayment: "", interestAmount: "", feesAmount: "", downPaymentConfirmed: false, count: "", periodicity: "", dueDate: "", customDates: "", rate: "", ratePeriod: "" }; }
function buildCreateRequest(draft: NewDraft): CreatePlanRequest {
  const financing = draft.financingMode === "confirmed" ? { confirmedBalance: { confirmed: draft.downPaymentConfirmed, downPaymentCents: decimalMoneyToCents(draft.downPayment), interestCents: decimalMoneyToCents(draft.interestAmount), feesCents: decimalMoneyToCents(draft.feesAmount) } } : draft.financingMode === "installment" ? { installmentAmountCents: decimalMoneyToCents(draft.installmentAmount) } : { totalFinancedCents: decimalMoneyToCents(draft.financedAmount) };
  const common = { currency: draft.currency, originalAmountCents: decimalMoneyToCents(draft.originalAmount), financing, ...(draft.rate ? { interestRate: { value: draft.rate, period: draft.ratePeriod } } : {}) };
  const planInput = draft.mode === "single" ? { ...common, mode: "single", dueDate: draft.dueDate || null } : { ...common, mode: "installments", installmentCount: Number(draft.count), schedule: draft.periodicity === "custom" ? { periodicity: "custom", dueDates: draft.customDates.split(/\s+/).filter(Boolean) } : { periodicity: draft.periodicity, firstDueDate: draft.dueDate } };
  return parseCreatePlanRequest({ requestId: crypto.randomUUID(), branchId: draft.branchId, creditor: draft.creditor, creditorType: draft.creditorType, takenAt: draft.takenAt, ...(draft.concept ? { concept: draft.concept } : {}), ...(draft.category ? { category: draft.category } : {}), ...(draft.reference ? { reference: draft.reference } : {}), ...(draft.notes ? { notes: draft.notes } : {}), ...(draft.expectedPaymentMethod ? { expectedPaymentMethod: draft.expectedPaymentMethod } : {}), planInput, scheduleConfirmed: true });
}
function NewDebtDrawer({ open, onClose, branches, today, onSaved, pending, onRetain, onClear, expectedSession, onSessionMismatch }: { open: boolean; onClose: () => void; branches: { id: string; name: string }[]; today: string; onSaved: () => void } & RecoveryProps) {
  const [draft, setDraft] = useState(() => initialDraft(today));
  const [review, setReview] = useState<{ request: CreatePlanRequest; plan: DebtPlan } | null>(() => pending?.kind === "create" ? { request: pending.request, plan: generateDebtPlan(pending.request.planInput) } : null);
  const [busy, setBusy] = useState(false);
  const lock = useRef(false);
  const [error, setError] = useState("");
  const [uncertain, setUncertain] = useState(!!pending);
  const set = (key: keyof NewDraft, value: string | boolean) => setDraft((current) => ({ ...current, [key]: value }));
  function preview(event: FormEvent) { event.preventDefault(); try { const request = buildCreateRequest(draft); setReview({ request, plan: generateDebtPlan(request.planInput) }); setError(""); } catch (cause) { setError(debtErrorMessage(cause)); } }
  async function save() {
    if (lock.current || !review) return;
    lock.current = true; setBusy(true); setError("");
    try { if (!onRetain({ kind: "create", request: review.request })) { setError("No se pudo guardar el identificador de recuperación. No se envió la operación."); return; } if (uncertain) { const result = await lookupOperation(operationReference({ kind: "create", request: review.request }), expectedSession); if (!result.ok) { if ("code" in result && ["session_changed", "no_session"].includes(String(result.code))) onSessionMismatch(); setError(result.error); return; } if (result.found) { onClear(review.request.requestId); setReview(null); setDraft(initialDraft(today)); setUncertain(false); onSaved(); return; } } const result = await createDebtPlanAction(review.request, expectedSession); if (result.ok) { onClear(review.request.requestId); setReview(null); setDraft(initialDraft(today)); setUncertain(false); onSaved(); } else { if ((!uncertain && !result.uncertain) || result.definitiveRejected) onClear(review.request.requestId); if (["session_changed", "no_session"].includes(result.code)) onSessionMismatch(); setError(result.error); if (result.definitiveRejected) setUncertain(false); else setUncertain((previous) => previous || !!result.uncertain); } }
    catch { setError("La conexión se interrumpió. Reintentá este mismo intento para recuperar el resultado sin duplicarlo."); setUncertain(true); }
    finally { lock.current = false; setBusy(false); }
  }
  return <Drawer open={open} onClose={() => { if (!lock.current) onClose(); }} title={review ? "Confirmar deuda y cronograma" : "Nueva deuda"} description="El borrador se conserva al cerrar. El intento enviado puede recuperarse en esta pestaña durante 24 h; después queda su referencia." width="max-w-3xl"><div className="space-y-5 p-6"><ErrorMessage error={error} />{review ? <>
    <div className="rounded-xl border border-line p-4 text-sm"><p className="font-semibold">{review.request.creditor} · {review.plan.mode === "single" ? "Pago único" : `${review.plan.installmentCount} cuotas`}</p><p>{review.request.concept ?? "Sin concepto"}</p><p>{branches.find((branch) => branch.id === review.request.branchId)?.name} · Origen: {date(review.request.takenAt)} · {CREDITOR_TYPES[review.request.creditorType]}</p><p className="mt-3">Capital original: {money(review.plan.originalAmountCents, review.plan.currency)}</p><p>Total a pagar en este cronograma: {money(review.plan.totalFinancedCents, review.plan.currency)}</p>{review.plan.confirmedBalance && <><p>Anticipo ya pagado: {money(review.plan.downPaymentCents!, review.plan.currency)}</p><p>Intereses: {money(review.plan.confirmedBalance.interestCents, review.plan.currency)} · Recargos: {money(review.plan.confirmedBalance.feesCents, review.plan.currency)}</p></>}{review.plan.interestRate && <p>Tasa informada: {review.plan.interestRate.value}% · {ratePeriods[review.plan.interestRate.period]}</p>}</div>
    <div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Cuota</th><th className="p-2">Vencimiento</th><th className="p-2">Importe</th></tr></thead><tbody>{review.plan.installments.map((part) => <tr key={part.installmentNumber} className="border-t border-line"><td className="p-2">{part.installmentNumber}</td><td className="p-2">{date(part.dueDate)}</td><td className="p-2">{money(part.totalAmountCents, review.plan.currency)}</td></tr>)}</tbody></table></div><p className="text-xs text-ink-muted">La última cuota absorbe las diferencias de centavos. No se inventa una amortización de capital/interés por cuota. Confirmar registra esta obligación; no mueve dinero.</p>
    <div className="flex flex-wrap gap-2"><Button disabled={busy || uncertain} onClick={() => { setReview(null); setError(""); }}>Volver a editar</Button><Button variant="primary" disabled={busy} onClick={save}><Check className="h-4 w-4" />{busy ? "Guardando…" : uncertain ? "Comprobar / reintentar el mismo intento" : "Confirmar y guardar cronograma"}</Button></div>
  </> : <form onSubmit={preview} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">
    <Field label="Acreedor *"><input required maxLength={200} className={inputClass} value={draft.creditor} onChange={(e) => set("creditor", e.target.value)} /></Field><Field label="Tipo de acreedor *"><select required className={inputClass} value={draft.creditorType} onChange={(e) => set("creditorType", e.target.value)}><option value="">Elegí un tipo</option>{Object.entries(CREDITOR_TYPES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>
    <Field label="Concepto / descripción"><input maxLength={1000} className={inputClass} value={draft.concept} onChange={(e) => set("concept", e.target.value)} /></Field><Field label="Sucursal *"><select required className={inputClass} value={draft.branchId} onChange={(e) => set("branchId", e.target.value)}><option value="">Elegí una sucursal</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field>
    <Field label="Moneda *" hint="Código de 3 letras. No se realizan conversiones."><input required pattern="[A-Z]{3}" maxLength={3} placeholder="ARS, USD, EUR…" className={inputClass} value={draft.currency} onChange={(e) => set("currency", e.target.value.toUpperCase())} /></Field><Field label="Fecha de origen *" hint={`Se muestra hoy (${date(today)}). Confirmá o cambiá esta fecha.`}><input required type="date" min="2000-01-01" className={inputClass} value={draft.takenAt} onChange={(e) => set("takenAt", e.target.value)} /></Field>
    <Field label="Modalidad *"><select className={inputClass} value={draft.mode} onChange={(e) => { set("mode", e.target.value); if (e.target.value === "single" && draft.financingMode === "installment") set("financingMode", "total"); }}><option value="single">Pago único</option><option value="installments">Plan de cuotas</option></select></Field><Field label="Monto original *" hint="Sin puntos de miles. Decimales con punto: 900000.50"><input required inputMode="decimal" className={inputClass} value={draft.originalAmount} onChange={(e) => set("originalAmount", e.target.value)} /></Field>
    <Field label="Cómo se define el saldo *"><select className={inputClass} value={draft.financingMode} onChange={(e) => set("financingMode", e.target.value)}><option value="total">Total financiado explícito</option>{draft.mode === "installments" && <option value="installment">Importe explícito por cuota</option>}<option value="confirmed">Capital − anticipo + cargos confirmados</option></select></Field>
    {draft.financingMode === "total" && <Field label="Total financiado / a pagar *" hint="Incluí los cargos acordados. No se infiere desde el capital."><input required inputMode="decimal" className={inputClass} value={draft.financedAmount} onChange={(e) => set("financedAmount", e.target.value)} /></Field>}
    {draft.financingMode === "installment" && <Field label="Importe por cuota *"><input required inputMode="decimal" className={inputClass} value={draft.installmentAmount} onChange={(e) => set("installmentAmount", e.target.value)} /></Field>}
    {draft.financingMode === "confirmed" && <><Field label="Anticipo ya pagado *" hint="Escribí 0 si no hubo anticipo."><input required inputMode="decimal" className={inputClass} value={draft.downPayment} onChange={(e) => set("downPayment", e.target.value)} /></Field><Field label="Interés total en dinero *" hint="Escribí 0 sólo si confirmás que no hay interés."><input required inputMode="decimal" className={inputClass} value={draft.interestAmount} onChange={(e) => set("interestAmount", e.target.value)} /></Field><Field label="Recargos totales *" hint="Escribí 0 sólo si confirmás que no hay recargos."><input required inputMode="decimal" className={inputClass} value={draft.feesAmount} onChange={(e) => set("feesAmount", e.target.value)} /></Field><label className="flex gap-2 text-xs text-ink-muted sm:col-span-2"><input required type="checkbox" checked={draft.downPaymentConfirmed} onChange={(e) => set("downPaymentConfirmed", e.target.checked)} />Confirmo que el anticipo indicado ya fue pagado y que estos importes incluyen todos los intereses y recargos acordados. El anticipo queda registrado como información histórica, fuera de las cuotas.</label></>}
    {draft.mode === "installments" && <><Field label="Cantidad de cuotas *"><input required type="number" min={1} max={1200} step={1} className={inputClass} value={draft.count} onChange={(e) => set("count", e.target.value)} /></Field><Field label="Periodicidad *"><select required className={inputClass} value={draft.periodicity} onChange={(e) => set("periodicity", e.target.value)}><option value="">Elegí una periodicidad</option><option value="weekly">Semanal (7 días)</option><option value="fortnightly">Quincenal (15 días)</option><option value="monthly">Mensual</option><option value="custom">Fechas personalizadas</option></select></Field></>}
    {draft.mode === "installments" && draft.periodicity === "custom" ? <Field label="Una fecha por cuota *" hint="Formato AAAA-MM-DD, una por línea y en orden."><textarea required rows={5} className={inputClass} placeholder={"2026-11-10\n2026-12-10"} value={draft.customDates} onChange={(e) => set("customDates", e.target.value)} /></Field> : <Field label={draft.mode === "single" ? "Vencimiento estimado (opcional)" : "Primer vencimiento *"}><input type="date" required={draft.mode === "installments"} className={inputClass} value={draft.dueDate} onChange={(e) => set("dueDate", e.target.value)} /></Field>}
    <Field label="Tasa de interés % (opcional)" hint="Informativa: no se convierte automáticamente a dinero."><input inputMode="decimal" className={inputClass} value={draft.rate} onChange={(e) => set("rate", e.target.value)} /></Field>{draft.rate && <Field label="Período de la tasa *"><select required className={inputClass} value={draft.ratePeriod} onChange={(e) => set("ratePeriod", e.target.value)}><option value="">Elegí el período</option>{Object.entries(ratePeriods).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>}
    <Field label="Categoría (opcional)"><select className={inputClass} value={draft.category} onChange={(e) => set("category", e.target.value)}><option value="">Sin categoría</option>{Object.entries(DEBT_CATEGORIES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Método de pago previsto (opcional)"><input maxLength={80} className={inputClass} value={draft.expectedPaymentMethod} onChange={(e) => set("expectedPaymentMethod", e.target.value)} /></Field><Field label="Referencia / número de operación"><input maxLength={200} className={inputClass} value={draft.reference} onChange={(e) => set("reference", e.target.value)} /></Field><Field label="Notas"><textarea maxLength={1000} className={inputClass} value={draft.notes} onChange={(e) => set("notes", e.target.value)} /></Field>
  </div><Button variant="primary" type="submit">Revisar cronograma antes de guardar</Button></form>}</div></Drawer>;
}

function PaymentDrawer({ open, onClose, debt, access, today, onSaved, onRefresh, pending, onRetain, onClear, expectedSession, onSessionMismatch }: { open: boolean; onClose: () => void; debt: DebtView; access: DebtAccess; today: string; onSaved: () => void; onRefresh: () => void } & RecoveryProps) {
  const [amount, setAmount] = useState("");
  const [paidAt, setPaidAt] = useState(today);
  const [method, setMethod] = useState("");
  const [reference, setReference] = useState("");
  const [notes, setNotes] = useState("");
  const [rule, setRule] = useState("");
  const [installmentId, setInstallmentId] = useState("");
  const [review, setReview] = useState<{ request: PaymentPlanRequest; allocations: DebtPaymentAllocation[] } | null>(() => pending?.kind === "pay" || pending?.kind === "legacy" ? { request: pending.request, allocations: [] } : null);
  const [error, setError] = useState("");
  const [uncertain, setUncertain] = useState(!!pending);
  const [legacyUnknown, setLegacyUnknown] = useState(pending?.kind === "legacy");
  const [legacyMatchedPayment, setLegacyMatchedPayment] = useState("");
  const [busy, setBusy] = useState(false);
  const lock = useRef(false);
  const [stale, setStale] = useState(false);
  function preview(event: FormEvent) {
    event.preventDefault();
    try {
      if (paidAt > today) throw new Error("future_payment");
      const request = parsePaymentPlanRequest({ requestId: crypto.randomUUID(), debtId: debt.id, expectedVersion: debt.ledger?.version ?? 0, amountCents: decimalMoneyToCents(amount), paidAt, paymentMethod: method, allocation: rule === "selected_installment" ? { rule, installmentId } : { rule }, ...(reference ? { reference } : {}), ...(notes ? { notes } : {}) });
      let allocations: DebtPaymentAllocation[] = [];
      if (debt.ledger) allocations = allocateDebtPayment(debt.ledger, { debtId: debt.id, businessId: debt.ledger.businessId, branchId: debt.branchId, paymentId: request.requestId, currency: debt.ledger.currency, expectedVersion: request.expectedVersion, amountCents: request.amountCents, paidAt: request.paidAt, paymentMethod: request.paymentMethod, allocation: request.allocation, origin: "manual", ...(request.reference ? { reference: request.reference } : {}), ...(request.notes ? { notes: request.notes } : {}) }, access).payment.allocations;
      else if (request.amountCents > debt.pendingCents) throw new Error("legacy_overpay");
      setReview({ request, allocations }); setError(""); setStale(false);
    } catch (cause) { setError(cause instanceof Error && cause.message === "future_payment" ? "Un pago realizado no puede tener fecha futura. Elegí la fecha efectiva del pago." : cause instanceof Error && cause.message === "legacy_overpay" ? "El pago supera el saldo de la deuda histórica." : debtErrorMessage(cause)); }
  }
  async function save() {
    if (lock.current || !review || legacyUnknown) return;
    lock.current = true; setBusy(true); setError("");
    try {
      if (!onRetain({ kind: debt.ledger ? "pay" : "legacy", request: review.request })) { setError("No se pudo guardar el identificador de recuperación. No se envió el pago."); return; }
      if (uncertain && debt.ledger) { const result = await lookupOperation(operationReference({ kind: "pay", request: review.request }), expectedSession); if (!result.ok) { if ("code" in result && ["session_changed", "no_session"].includes(String(result.code))) onSessionMismatch(); setError(result.error); return; } if (result.found) { onClear(review.request.requestId); setReview(null); setAmount(""); setUncertain(false); onSaved(); return; } }
      const action = debt.ledger ? registerDebtPlanPaymentAction : registerLegacyDebtPaymentAction;
      const result = await action(review.request, expectedSession);
      if (result.ok) { onClear(review.request.requestId); setReview(null); setAmount(""); setMethod(""); setReference(""); setNotes(""); setRule(""); setInstallmentId(""); setUncertain(false); onSaved(); }
      else { if ((!uncertain && !result.uncertain) || result.definitiveRejected) onClear(review.request.requestId); if (["session_changed", "no_session"].includes(result.code)) onSessionMismatch(); setError(result.error); if (result.definitiveRejected) setUncertain(false); else setUncertain((previous) => previous || !!result.uncertain); setLegacyUnknown((previous) => previous || (!debt.ledger && !!result.uncertain)); if (["stale_version", "version_conflict"].includes(result.code)) { setStale(true); onRefresh(); } }
    } catch { setError(debt.ledger ? "La conexión se interrumpió. Reintentá el mismo intento para recuperar el resultado sin duplicarlo." : "No pudimos confirmar este pago histórico. Revisá el historial antes de registrar otro. No se habilitan reintentos automáticos."); setUncertain(true); setLegacyUnknown(!debt.ledger); }
    finally { lock.current = false; setBusy(false); }
  }
  return <Drawer open={open} onClose={() => { if (!lock.current) onClose(); }} title={`Registrar pago · ${debt.creditor}`} description="Registro interno de un pago realizado. No mueve dinero." width="max-w-2xl"><div className="space-y-4 p-6"><p className="text-sm">Saldo actual: {money(debt.pendingCents, debt.currency)}</p><ErrorMessage error={error} />{review ? <>
    <div className="space-y-2 rounded-xl border border-line p-4 text-sm"><p className="font-semibold">Pago: {money(review.request.amountCents, debt.currency)}</p><p>Fecha efectiva: {date(review.request.paidAt)}</p><p>Método: {review.request.paymentMethod}</p><p>Imputación: {review.request.allocation.rule === "selected_installment" ? `Sólo cuota ${debt.ledger?.installments.find((part) => part.id === (review.request.allocation as { installmentId: string }).installmentId)?.installmentNumber}` : debt.ledger ? "Cuotas pendientes más antiguas por vencimiento; incluye anticipos a futuras cuotas si alcanza." : "Saldo global de esta deuda histórica, sin cuotas."}</p>{review.allocations.map((allocation) => <p key={allocation.installmentId}>Cuota {debt.ledger?.installments.find((part) => part.id === allocation.installmentId)?.installmentNumber} · {money(allocation.amountCents, debt.currency)}</p>)}{review.request.reference && <p>Referencia: {review.request.reference}</p>}{review.request.notes && <p className="whitespace-pre-wrap">{review.request.notes}</p>}</div>
    {legacyUnknown ? <div className="space-y-3 text-xs text-ink-muted"><p>Conservamos los datos del intento. El sistema histórico no tiene identificadores de reintento: verificá el importe, la fecha y el método en el historial antes de iniciar otro pago.</p><Button onClick={onRefresh}>Actualizar historial</Button><div className="max-h-48 overflow-auto">{debt.payments.map((payment) => <p key={payment.id} className="border-t border-line py-2">{money(storedMoney(payment.amount), debt.currency)} · {date(payment.paid_at)} · {payment.payment_method} · {payment.created_at}</p>)}</div><Field label="Pago histórico verificado"><select className={inputClass} value={legacyMatchedPayment} onChange={(event) => setLegacyMatchedPayment(event.target.value)}><option value="">Elegí el registro que corresponde a este intento</option>{debt.payments.map((payment) => <option key={payment.id} value={payment.id}>{money(storedMoney(payment.amount), debt.currency)} · {date(payment.paid_at)} · {payment.payment_method} · {payment.id}</option>)}</select></Field><Button disabled={!debt.payments.some((payment) => payment.id === legacyMatchedPayment)} onClick={() => { if (!debt.payments.some((payment) => payment.id === legacyMatchedPayment)) return; onClear(review.request.requestId); setLegacyUnknown(false); setUncertain(false); setReview(null); setAmount(""); setMethod(""); setReference(""); setNotes(""); setError(""); onSaved(); }}>Confirmar pago histórico verificado</Button><p>Si no encontrás un resultado confirmado, conservamos el intento pendiente. No se habilita otro UUID para repetirlo.</p></div> : <div className="flex flex-wrap gap-2"><Button disabled={busy || uncertain} onClick={() => { setReview(null); setError(""); if (stale) onRefresh(); }}>Volver a revisar</Button><Button disabled={busy || (stale && !uncertain)} variant="primary" onClick={save}>{busy ? "Registrando…" : uncertain ? "Comprobar / reintentar el mismo pago" : "Confirmar registro del pago"}</Button></div>}
  </> : <form onSubmit={preview} className="space-y-4"><Field label="Importe pagado *" hint="Sin separador de miles, con punto decimal. Podés registrar un pago parcial."><input required inputMode="decimal" className={inputClass} value={amount} onChange={(e) => setAmount(e.target.value)} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Fecha efectiva del pago *" hint={`Se muestra hoy (${date(today)}). Confirmá o cambiá la fecha.`}><input required type="date" min="2000-01-01" max={today} className={inputClass} value={paidAt} onChange={(e) => setPaidAt(e.target.value)} /></Field><Field label="Método usado *" hint="Ingresalo expresamente; no se supone un método."><input required maxLength={80} className={inputClass} placeholder="Ej.: transferencia, efectivo…" value={method} onChange={(e) => setMethod(e.target.value)} /></Field></div><Field label="Regla de imputación *"><select required className={inputClass} value={rule} onChange={(e) => setRule(e.target.value)}><option value="">Elegí cómo aplicar este pago</option>{debt.ledger && <option value="selected_installment">A una cuota seleccionada, incluso anticipada</option>}<option value="oldest_due">{debt.ledger ? "Global: cuotas pendientes más antiguas" : "Global: saldo de esta deuda histórica"}</option></select></Field>{rule === "selected_installment" && <Field label="Cuota *"><select required className={inputClass} value={installmentId} onChange={(e) => setInstallmentId(e.target.value)}><option value="">Elegí la cuota</option>{debt.projection?.installments.filter((part) => part.pendingAmountCents > 0).map((part) => <option key={part.id} value={part.id}>Cuota {part.installmentNumber} · {date(part.dueDate)} · saldo {money(part.pendingAmountCents, debt.currency)}</option>)}</select></Field>}<Field label="Comprobante / referencia (opcional)"><input maxLength={200} className={inputClass} value={reference} onChange={(e) => setReference(e.target.value)} /></Field><Field label="Notas (opcional)"><textarea maxLength={1000} className={inputClass} value={notes} onChange={(e) => setNotes(e.target.value)} /></Field><Button type="submit" variant="primary">Revisar pago e imputación</Button></form>}</div></Drawer>;
}

function VoidPaymentForm({ open, debt, paymentId, onClose, onSaved, pending, onRetain, onClear, expectedSession, onSessionMismatch }: { open: boolean; debt: DebtView; paymentId: string; onClose: () => void; onSaved: () => void } & RecoveryProps) {
  const router = useRouter();
  const [reason, setReason] = useState("");
  const [review, setReview] = useState<VoidPlanRequest | null>(() => pending?.kind === "void" ? pending.request : null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [uncertain, setUncertain] = useState(!!pending);
  const [stale, setStale] = useState(false);
  const lock = useRef(false);
  const payment = debt.payments.find((item) => item.id === paymentId);
  async function submit() {
    if (lock.current || !review) return;
    lock.current = true; setBusy(true); setError("");
    try { if (!onRetain({ kind: "void", request: review })) { setError("No se pudo guardar el identificador de recuperación. No se envió la anulación."); return; } if (uncertain) { const result = await lookupOperation(operationReference({ kind: "void", request: review }), expectedSession); if (!result.ok) { if ("code" in result && ["session_changed", "no_session"].includes(String(result.code))) onSessionMismatch(); setError(result.error); return; } if (result.found) { onClear(review.requestId); onSaved(); return; } } const result = await voidDebtPlanPaymentAction(review, expectedSession); if (result.ok) { onClear(review.requestId); onSaved(); } else { if ((!uncertain && !result.uncertain) || result.definitiveRejected) onClear(review.requestId); if (["session_changed", "no_session"].includes(result.code)) onSessionMismatch(); setError(result.error); if (result.definitiveRejected) setUncertain(false); else setUncertain((previous) => previous || !!result.uncertain); if (["stale_version", "version_conflict"].includes(result.code)) { setStale(true); router.refresh(); } } }
    catch { setError("La conexión se interrumpió. Reintentá la misma anulación para verificar su resultado."); setUncertain(true); }
    finally { lock.current = false; setBusy(false); }
  }
  return <Drawer open={open} onClose={() => { if (!lock.current) onClose(); }} title={`Anular pago · ${debt.creditor}`} description="El motivo y el identificador del intento se conservan al cerrar."><div role="region" aria-label="Anulación del pago" className="m-6 space-y-3 rounded-xl border border-danger-500/40 p-4"><h3 className="font-semibold">Anular pago</h3><p className="text-sm">{payment ? `${money(storedMoney(payment.amount), debt.currency)} · ${date(payment.paid_at)} · ${payment.payment_method}` : "Pago seleccionado"}. Se conservará el registro y se reabrirán los saldos afectados. No se devuelve dinero.</p><ErrorMessage error={error} />{review ? <><p className="whitespace-pre-wrap text-sm">Motivo: {review.reason}</p><div className="flex gap-2"><Button disabled={busy || uncertain} onClick={() => { setReview(null); setStale(false); setError(""); }}>Revisar</Button><Button disabled={busy || (stale && !uncertain)} onClick={submit}>{busy ? "Anulando…" : uncertain ? "Comprobar misma anulación" : "Confirmar anulación"}</Button></div></> : <form onSubmit={(event) => { event.preventDefault(); try { setReview(parseVoidPlanRequest({ requestId: crypto.randomUUID(), debtId: debt.id, paymentId, expectedVersion: debt.ledger?.version, reason })); setError(""); } catch (cause) { setError(debtErrorMessage(cause)); } }} className="space-y-3"><Field label="Motivo obligatorio"><textarea required maxLength={1000} className={inputClass} value={reason} onChange={(e) => setReason(e.target.value)} /></Field><div className="flex gap-2"><Button onClick={onClose} type="button">Cancelar</Button><Button type="submit">Revisar anulación</Button></div></form>}</div></Drawer>;
}

function EditDebtDrawer({ open, debt, installmentId, onClose, onSaved, pending, onRetain, onClear, expectedSession, onSessionMismatch }: { open: boolean; debt: DebtView; installmentId: string | null; onClose: () => void; onSaved: () => void } & RecoveryProps) {
  const router = useRouter();
  const installment = debt.projection?.installments.find((part) => part.id === installmentId);
  const [notes, setNotes] = useState(() => installmentId ? debt.components.find((part) => part.id === installmentId)?.notes ?? "" : debt.notes ?? "");
  const [dueDate, setDueDate] = useState(installment?.dueDate ?? "");
  const [review, setReview] = useState<EditPlanRequest | null>(() => pending?.kind === "edit" ? pending.request : null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [uncertain, setUncertain] = useState(!!pending);
  const [stale, setStale] = useState(false);
  const lock = useRef(false);
  function preview(event: FormEvent) {
    event.preventDefault();
    try {
      if (installmentId && debt.ledger?.mode === "installments" && !dueDate) throw new Error("due_date_required");
      const request = parseEditPlanRequest({ requestId: crypto.randomUUID(), debtId: debt.id, expectedVersion: debt.ledger?.version, notes: notes.trim() || null, ...(installmentId ? { kind: "installment", installmentId, dueDate: dueDate || null } : { kind: "notes" }) });
      if (request.kind === "installment" && request.dueDate) {
        const parts = debt.projection?.installments ?? [];
        const index = parts.findIndex((part) => part.id === request.installmentId);
        if ((index > 0 && parts[index - 1].dueDate && request.dueDate <= parts[index - 1].dueDate!) || (index < parts.length - 1 && parts[index + 1].dueDate && request.dueDate >= parts[index + 1].dueDate!)) throw new Error("dates_not_increasing");
      }
      setReview(request); setError(""); setStale(false);
    } catch (cause) { setError(cause instanceof Error && cause.message === "dates_not_increasing" ? "El vencimiento debe ser posterior a la cuota anterior y anterior a la siguiente." : debtErrorMessage(cause)); }
  }
  async function save() {
    if (lock.current || !review) return;
    lock.current = true; setBusy(true); setError("");
    try {
      if (!onRetain({ kind: "edit", request: review })) { setError("No se pudo guardar el identificador de recuperación. No se envió la edición."); return; }
      if (uncertain) { const result = await lookupOperation(operationReference({ kind: "edit", request: review }), expectedSession); if (!result.ok) { if ("code" in result && ["session_changed", "no_session"].includes(String(result.code))) onSessionMismatch(); setError(result.error); return; } if (result.found) { onClear(review.requestId); setReview(null); setUncertain(false); onSaved(); return; } }
      const result = await editDebtPlanAction(review, expectedSession);
      if (result.ok) { onClear(review.requestId); setReview(null); setUncertain(false); onSaved(); }
      else { if ((!uncertain && !result.uncertain) || result.definitiveRejected) onClear(review.requestId); if (["session_changed", "no_session"].includes(result.code)) onSessionMismatch(); setError(result.error); if (result.definitiveRejected) setUncertain(false); else setUncertain((previous) => previous || !!result.uncertain); if (["stale_version", "version_conflict"].includes(result.code)) { setStale(true); router.refresh(); } }
    } catch { setError("La conexión se interrumpió. Comprobá la misma edición para recuperar su resultado sin duplicarla."); setUncertain(true); }
    finally { lock.current = false; setBusy(false); }
  }
  return <Drawer open={open} onClose={() => { if (!lock.current) onClose(); }} title={installmentId ? `Editar cuota ${installment?.installmentNumber ?? ""} · ${debt.creditor}` : `Editar notas · ${debt.creditor}`} description="Los importes y condiciones financieras permanecen registrados. Toda edición guarda auditoría."><div className="space-y-4 p-6"><ErrorMessage error={error} />{review ? <><p className="text-sm">{review.kind === "installment" ? `Nuevo vencimiento: ${date(review.dueDate)}` : "Notas de la deuda"}</p><p className="whitespace-pre-wrap text-sm">Notas: {review.notes ?? "Sin notas (se eliminará el texto anterior)"}</p><div className="flex gap-2"><Button disabled={busy || uncertain} onClick={() => { setReview(null); setError(""); setStale(false); }}>Volver a revisar</Button><Button variant="primary" disabled={busy || (stale && !uncertain)} onClick={save}>{busy ? "Guardando…" : uncertain ? "Comprobar la misma edición" : "Confirmar edición"}</Button></div></> : <form onSubmit={preview} className="space-y-4">{installmentId && <Field label="Nuevo vencimiento" hint="Las fechas deben mantener el orden de las cuotas."><input type="date" required={debt.ledger?.mode === "installments"} className={inputClass} value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></Field>}<Field label="Notas" hint="Dejá vacío para borrar las notas anteriores. El historial conserva el cambio."><textarea maxLength={1000} className={inputClass} value={notes} onChange={(event) => setNotes(event.target.value)} /></Field><Button type="submit" variant="primary">Revisar edición</Button></form>}</div></Drawer>;
}

function CancelDebtForm({ open, debt, pending, onClose, onSaved, onRetain, onClear, expectedSession, onSessionMismatch }: { open: boolean; debt: DebtView; onClose: () => void; onSaved: () => void } & RecoveryProps) {
  const router = useRouter();
  const [reason, setReason] = useState(pending?.kind === "cancel" ? pending.request.reason : "");
  const [confirmed, setConfirmed] = useState(false);
  const [review, setReview] = useState<CancelPlanRequest | null>(pending?.kind === "cancel" ? pending.request : null);
  const [uncertain, setUncertain] = useState(pending?.kind === "cancel");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const lock = useRef(false);
  async function save() {
    if (lock.current || !review) return;
    lock.current = true; setBusy(true); setError("");
    try {
      if (!onRetain({ kind: "cancel", request: review })) { setError("No se pudo conservar el intento de cancelación. No se envió la operación."); return; }
      if (uncertain) {
        const result = await lookupOperation(operationReference({ kind: "cancel", request: review }), expectedSession);
        if (!result.ok) { if (["session_changed", "no_session"].includes(result.code ?? "")) onSessionMismatch(); setError(result.error); return; }
        if (result.found) { onClear(review.requestId); setReview(null); setUncertain(false); onSaved(); return; }
      }
      const result = await cancelDebtPlanRecordAction(review, expectedSession);
      if (result.ok) { onClear(review.requestId); setReview(null); setUncertain(false); onSaved(); }
      else {
        if ((!uncertain && !result.uncertain) || result.definitiveRejected) onClear(review.requestId);
        if (["session_changed", "no_session"].includes(result.code)) onSessionMismatch();
        setError(result.error);
        if (["stale_version", "debt_cancelled"].includes(result.code)) router.refresh();
        setUncertain(result.definitiveRejected ? false : uncertain || !!result.uncertain);
      }
    } catch { setError("No pudimos confirmar la cancelación. Comprobá este mismo intento para recuperar el resultado sin duplicarlo."); setUncertain(true); }
    finally { lock.current = false; setBusy(false); }
  }
  function preview(event: FormEvent) {
    event.preventDefault();
    try { setReview(parseCancelPlanRequest({ requestId: crypto.randomUUID(), debtId: debt.id, expectedVersion: debt.ledger?.version, reason, administrativeOnlyConfirmed: confirmed })); setError(""); }
    catch (cause) { setError(debtErrorMessage(cause)); }
  }
  return <Drawer open={open} onClose={() => { if (!lock.current) onClose(); }} title={`Cancelar registro · ${debt.creditor}`} description="Cancelación administrativa interna. No realiza pagos ni extingue deudas con terceros."><div className="space-y-4 p-6"><ErrorMessage error={error} /><div className="space-y-2 rounded-lg border border-warning-500/30 p-3 text-sm"><p>Este registro se retirará de los compromisos activos y quedará cerrado para nuevos pagos y ediciones.</p><p>Se conservarán el cronograma, todos los pagos y el saldo histórico de {money(debt.pendingCents, debt.currency)}.</p><p>Esto no acredita que el acreedor haya perdonado la deuda ni realiza transferencias. Para registrar una cancelación anticipada mediante pago, usá el registro de pago global.</p></div>{review ? <><p className="text-sm">Motivo: {review.reason}</p><div className="flex flex-wrap gap-2"><Button disabled={busy || uncertain} onClick={() => { setReview(null); setError(""); }}>Volver a revisar cancelación</Button><Button variant="primary" disabled={busy} onClick={save}>{busy ? "Cancelando registro…" : uncertain ? "Comprobar / reintentar la misma cancelación" : "Confirmar cancelación administrativa"}</Button></div></> : <form onSubmit={preview} className="space-y-4"><Field label="Motivo de cancelación *"><textarea required maxLength={1000} className={inputClass} value={reason} onChange={(event) => setReason(event.target.value)} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" required checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />Confirmo que sólo cancelo este registro administrativo; no registro un pago ni una condonación del acreedor.</label><Button type="submit" variant="primary">Revisar cancelación administrativa</Button></form>}</div></Drawer>;
}
