import { decimalMoneyToCents, projectDebtCommitments, validateDebtLedger, type DebtAccess, type DebtLedgerSnapshot, type DebtOrigin, type DebtProjection, type DebtPlan } from "../../lib/debts/plans";

export type DebtRow = { id: string; business_id: string; branch_id: string | null; creditor: string; creditor_type: string | null; concept: string | null; currency: string | null; original_amount: string | number; pending_amount: string | number; taken_at: string; due_date: string | null; status: string; origin: string | null; category: string | null; reference: string | null; notes: string | null; expected_payment_method: string | null; total_financed_amount: string | number | null; down_payment_amount: string | number | null; mode: "single" | "installments"; plan_version: number; plan_definition: DebtPlan | null; created_by: string | null; created_at: string };
export type InstallmentRow = { id: string; business_id: string; branch_id: string | null; debt_id: string; installment_number: number; due_date: string | null; total_amount: string | number; capital_amount: string | number | null; interest_amount: string | number | null; fees_amount: string | number | null; notes: string | null };
export type PaymentRow = { id: string; business_id: string; branch_id: string | null; debt_id: string; amount: string | number; currency: string | null; paid_at: string; payment_method: string; created_by: string | null; created_at: string; origin: DebtOrigin | null; reference: string | null; notes: string | null; allocation_rule: "oldest_due" | "selected_installment" | null; selected_installment_id: string | null; voided_at: string | null; voided_on: string | null; voided_by: string | null; void_reason: string | null };
export type AllocationRow = { business_id: string; branch_id: string | null; debt_id: string; payment_id: string; installment_id: string; amount: string | number };
export type DebtAuditRow = { id: string; target_id: string; actor_id: string | null; action: string; summary: string; created_at: string; data?: Record<string, unknown> };
export type DebtView = { id: string; creditor: string; creditorType: string | null; concept: string | null; currency: string | null; branchId: string | null; takenAt: string; origin: string | null; category: string | null; reference: string | null; notes: string | null; expectedPaymentMethod: string | null; createdBy: string | null; createdAt: string; originalCents: number; pendingCents: number; dueDate: string | null; status: string; ledger: DebtLedgerSnapshot | null; projection: DebtProjection | null; plan: DebtPlan | null; payments: PaymentRow[]; components: { id: string; capitalCents: number | null; interestCents: number | null; feesCents: number | null; notes: string | null }[]; audit: DebtAuditRow[] };
export function storedMoney(value: string | number): number { return decimalMoneyToCents(String(value)); }

export function mapDebtView(row: DebtRow, installments: InstallmentRow[], payments: PaymentRow[], allocations: AllocationRow[], audit: DebtAuditRow[], asOfDate: string, access: DebtAccess): DebtView {
  if (row.business_id !== access.businessId || (access.branchIds !== null && (!row.branch_id || !access.branchIds.includes(row.branch_id)))) throw new Error("debt_scope_mismatch");
  const parts = installments.filter((part) => part.debt_id === row.id);
  const history = payments.filter((payment) => payment.debt_id === row.id);
  for (const payment of history) if (payment.business_id !== row.business_id || payment.branch_id !== row.branch_id) throw new Error("payment_scope_mismatch");
  for (const allocation of allocations.filter((item) => item.debt_id === row.id)) if (!history.some((payment) => payment.id === allocation.payment_id)) throw new Error("orphan_allocation");
  const scope = { debtId: row.id, businessId: row.business_id, branchId: row.branch_id };
  const relatedAudit = audit.filter((event) => event.target_id === row.id || history.some((payment) => event.target_id === payment.id));
  const base = { id: row.id, creditor: row.creditor, creditorType: row.creditor_type, concept: row.concept, currency: row.currency, branchId: row.branch_id, takenAt: row.taken_at, origin: row.origin, category: row.category, reference: row.reference, notes: row.notes, expectedPaymentMethod: row.expected_payment_method, createdBy: row.created_by, createdAt: row.created_at, originalCents: storedMoney(row.original_amount), pendingCents: storedMoney(row.pending_amount), dueDate: row.due_date, status: row.status, payments: history, audit: relatedAudit };
  if (!row.plan_definition) return { ...base, ledger: null, projection: null, plan: null, components: [] };
  const ledger = validateDebtLedger({ ...scope, mode: row.mode, currency: row.currency, totalFinancedCents: storedMoney(row.total_financed_amount!), version: row.plan_version,
    installments: parts.map((part) => ({ id: part.id, businessId: part.business_id, debtId: part.debt_id, branchId: part.branch_id, installmentNumber: part.installment_number, dueDate: part.due_date, totalAmountCents: storedMoney(part.total_amount) })),
    payments: history.map((payment) => {
      const splits = allocations.filter((allocation) => allocation.payment_id === payment.id);
      for (const split of splits) if (split.business_id !== scope.businessId || split.debt_id !== scope.debtId || split.branch_id !== scope.branchId) throw new Error("allocation_scope_mismatch");
      return { id: payment.id, businessId: payment.business_id, debtId: payment.debt_id, branchId: payment.branch_id, currency: payment.currency, amountCents: storedMoney(payment.amount), paidAt: payment.paid_at, paymentMethod: payment.payment_method, actorId: payment.created_by, origin: payment.origin, ...(payment.reference ? { reference: payment.reference } : {}), ...(payment.notes ? { notes: payment.notes } : {}), allocation: payment.allocation_rule === "oldest_due" ? { rule: "oldest_due" } : { rule: payment.allocation_rule, installmentId: payment.selected_installment_id }, allocations: splits.map((part) => ({ installmentId: part.installment_id, amountCents: storedMoney(part.amount) })), ...(payment.voided_at ? { voided: { voidedAt: payment.voided_on, actorId: payment.voided_by, reason: payment.void_reason } } : {}) };
    }),
  });
  const projection = projectDebtCommitments(ledger, asOfDate, access);
  if (row.plan_definition.totalFinancedCents !== ledger.totalFinancedCents || row.plan_definition.originalAmountCents !== base.originalCents || row.plan_definition.currency !== ledger.currency) throw new Error("plan_definition_mismatch");
  if (projection.pendingAmountCents !== base.pendingCents) throw new Error("ledger_balance_mismatch");
  return { ...base, status: projection.status, ledger, projection, plan: row.plan_definition, components: parts.map((part) => ({ id: part.id, notes: part.notes, capitalCents: part.capital_amount === null ? null : storedMoney(part.capital_amount), interestCents: part.interest_amount === null ? null : storedMoney(part.interest_amount), feesCents: part.fees_amount === null ? null : storedMoney(part.fees_amount) })) };
}
