import test from "node:test";
import assert from "node:assert/strict";
import Module from "node:module";
import { hasPermission, canSeeModule } from "../lib/permissions";
import * as domain from "../lib/closures/domain";
const id = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const state = { database: true, authenticated: true, active: true, role: "owner", userId: id(1), businessId: id(2), enabled: ["daily_closures"], failure: "", calls: [] as any[], paths: [] as string[], revisions: [] as string[], countMismatch: false, cacheThrows: false };
const db: any = { rpc: async (name: string, args: unknown) => { state.calls.push({name,args}); if(name === "get_closures_revision") return {data: state.revisions.shift() ?? "0",error:null}; return {data:{ok:true,id:id(10),version:1},error:null}; }, from: (table: string) => { let single = false; const q:any = {select:()=>q,eq:()=>q,in:()=>q,order:()=>q,range:()=>q,maybeSingle:()=>{single=true;return q;},then:(resolve:any)=>{const data = table === "profiles" ? [{active:state.active}] : table === "businesses" ? [{timezone:"UTC"}] : table === "branches" ? [{id:id(3),name:"Branch"}] : table === "daily_closures" ? [{id:id(10),gross_total:"100.10",net_total:"-0.10"}] : []; return Promise.resolve({data:single?data[0]??null:data,error:state.failure?{code:"fail"}:null,count:state.countMismatch?undefined:data.length}).then(resolve);}}; return q;}};
const loader=Module as any; const original=loader._load;
loader._load=function(name:string,...args:any[]){const mocks:any={"next/cache":{revalidatePath:(path:string)=>{state.paths.push(path);if(state.cacheThrows)throw new Error("cache");}},"@/lib/data/auth":{getCurrentUserContext:async()=>({isAuthenticated:state.authenticated,userId:state.userId,businessId:state.businessId,role:state.role,enabledModules:state.enabled,assignedBranchIds:null})},"@/lib/supabase/server":{createSupabaseServerClient:async()=>db},"@/lib/env":{isDatabaseMode:()=>state.database},"@/lib/permissions":{hasPermission,canSeeModule},"@/lib/closures/domain":domain};return name in mocks?mocks[name]:original.call(this,name,...args);};
const actions=require("../app/actions/closures") as typeof import("../app/actions/closures");loader._load=original;
function reset(){Object.assign(state,{database:true,authenticated:true,active:true,role:"owner",userId:id(1),businessId:id(2),enabled:["daily_closures"],failure:"",calls:[],paths:[],revisions:[],countMismatch:false,cacheThrows:false});}
const input=()=>({requestId:id(9),businessId:id(2),userId:id(1),id:null,expectedVersion:null,branchId:id(3),closureDate:"2026-01-01",grossTotal:"100.10",netTotal:"-0.10",note:"",reason:null});
test("closure action invokes one atomic mutation, invalidates real reads, and retains success after cache failure",async()=>{reset(); assert.equal((await actions.saveClosureAction(input())).ok,true); assert.equal(state.calls.length,1);assert.equal(state.calls[0].name,"save_closure_atomic");assert.deepEqual(state.paths,["/cierres","/auditoria","/"]);reset();state.cacheThrows=true;assert.equal((await actions.saveClosureAction(input())).ok,true);});
test("closure mutation denies demo, missing session, inactive profiles, wrong role, disabled module and switched context",async()=>{for(const change of [()=>{state.database=false;},()=>{state.authenticated=false;},()=>{state.active=false;},()=>{state.role="viewer";},()=>{state.role="accountant";},()=>{state.role="waiter";},()=>{state.enabled=[];},()=>{state.userId=id(20);},()=>{state.businessId=id(20);}]){reset();change(); assert.equal((await actions.saveClosureAction(input())).ok,false);assert.equal(state.calls.length,0);}});
test("closure workspace rejects incomplete or changed reads and preserves textual amounts",async()=>{reset();let result=await actions.getClosuresWorkspaceAction();assert.equal(result.ok,true);if(result.ok)assert.equal(result.data.closures[0].gross_total,"100.10");assert.equal(state.calls.length,2);reset();state.revisions=["1","2"];result=await actions.getClosuresWorkspaceAction();assert.equal(result.ok,false);reset();state.countMismatch=true;assert.equal((await actions.getClosuresWorkspaceAction()).ok,false);reset();state.active=false;assert.equal((await actions.getClosuresWorkspaceAction()).ok,false);});
