import path from 'node:path';
import { assert, clickTwice, editorReady, noOverflow, releaseWrites, root, runUiHarness, viewports } from '../scripts/ui-fixtures/harness.mjs';
await runUiHarness({name:'closures',actionModules:{'@/app/actions/closures':path.join(root,'tests/closures-ui-fixture.mjs')},entry:`import React from 'react';import{createRoot}from'react-dom/client';import Page from '${root}/app/cierres/database-closures.tsx';createRoot(document.getElementById('root')).render(<Page/>);`,async run({page,origin,check,screenshot}){
 const open=async()=>{await page.getByRole('button',{name:'Nuevo cierre',exact:true}).click();return editorReady(page);};
 const fill=async(editor,note)=>{await editor.getByLabel('Sucursal',{exact:true}).selectOption({label:'Central QA ficticia'});await editor.getByLabel('Fecha del cierre',{exact:true}).fill('2026-01-02');await editor.getByLabel('Total bruto',{exact:true}).fill('123.45');await editor.getByLabel('Total neto',{exact:true}).fill('-0.10');await editor.getByLabel('Notas del cierre',{exact:true}).fill(note);};
 const close=async editor=>{await editor.getByRole('button',{name:/^(Cancelar|Cerrar y revisar)$/}).click();await editor.waitFor({state:'hidden'});};
 for(const viewport of viewports){await page.setViewportSize({width:viewport.width,height:viewport.height});await page.goto(origin);await page.getByText('Origen no informado',{exact:false}).first().waitFor();
 await check(`${viewport.name}: cancel and original historical detail`,async()=>{let editor=await open();assert.equal(await editor.getByLabel('Fecha del cierre').inputValue(),'');await fill(editor,'Descartado');await close(editor);assert.equal(await page.evaluate(()=>window.qa.saveCalls),0);await page.getByRole('button',{name:'Detalle e historial',exact:true}).first().click();editor=await editorReady(page);await editor.getByText('Original histórico QA ficticio',{exact:true}).waitFor();await noOverflow(page);await screenshot(`${viewport.name}-historical`);await editor.getByRole('button',{name:'Cerrar detalle',exact:true}).click();await editor.waitFor({state:'hidden'});});
 await check(`${viewport.name}: repeated click, close while saving, signed amounts`,async()=>{const editor=await open();await fill(editor,'Nuevo cierre QA ficticio');await page.evaluate(()=>{window.qa.holdWrites=true;});await clickTwice(editor.getByRole('button',{name:'Guardar cierre',exact:true}));await page.waitForFunction(()=>window.qa.saveCalls===1);await editor.getByRole('button',{name:'Cerrar',exact:true}).click();assert.equal(await editor.isVisible(),true);await releaseWrites(page);await editor.waitFor({state:'hidden'});await page.getByText('Nuevo cierre QA ficticio',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.qa.saveCalls),1);await screenshot(`${viewport.name}-created`);});
 await check(`${viewport.name}: correction reason and preserved original`,async()=>{const card=page.locator('.card').filter({has:page.getByText('Nuevo cierre QA ficticio',{exact:true})}).last();await card.getByRole('button',{name:'Corregir',exact:true}).click();const editor=await editorReady(page);assert.equal(await editor.getByLabel('Sucursal',{exact:true}).isDisabled(),true);await editor.getByLabel('Notas del cierre',{exact:true}).fill('Corregido QA ficticio');await editor.getByLabel('Motivo de corrección',{exact:true}).fill('Ajuste documentado');await editor.getByRole('button',{name:'Guardar cierre',exact:true}).click();await editor.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.qa.closures.find(c=>c.manual_note==='Corregido QA ficticio').raw_text),'Nuevo cierre QA ficticio');});
 await check(`${viewport.name}: uncertain operation freezes and replays exact attempt`,async()=>{const editor=await open();await fill(editor,'Incierto QA ficticio');await page.evaluate(()=>{window.qa.response='throw-after-commit';});await editor.getByRole('button',{name:'Guardar cierre',exact:true}).click();await editor.getByText(/No pudimos confirmar el resultado/).waitFor();assert.equal(await editor.getByLabel('Notas del cierre',{exact:true}).isDisabled(),true);await screenshot(`${viewport.name}-uncertain`);await close(editor);assert.equal(await page.getByRole('button',{name:'Nuevo cierre',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Reintentar mismo intento',exact:true}).click();await page.getByText(/Hay un cierre pendiente/).waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.qa.closures.filter(c=>c.manual_note==='Incierto QA ficticio').length),1);assert.deepEqual(await page.evaluate(()=>window.qa.writes.at(-1).input),await page.evaluate(()=>window.qa.writes.at(-2).input));});
 await check(`${viewport.name}: archive keeps record and audit`,async()=>{await page.getByRole('button',{name:'Archivar',exact:true}).first().click();const editor=await editorReady(page);assert.equal(await editor.getByRole('button',{name:'Confirmar archivo'}).isDisabled(),true);await editor.getByLabel('Motivo de archivo').fill('Duplicado QA ficticio');await clickTwice(editor.getByRole('button',{name:'Confirmar archivo'}));await editor.waitFor({state:'hidden'});await page.getByLabel('Estado de los cierres').selectOption('archived');await page.getByText('Motivo de archivo: Duplicado QA ficticio',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.qa.archiveCalls),1);await screenshot(`${viewport.name}-archive`);await page.getByLabel('Estado de los cierres').selectOption('active');});
 await check(`${viewport.name}: changed identity clears editor and errors hide stale rows`,async()=>{const editor=await open();await fill(editor,'Draft old session');await page.evaluate(()=>{window.qa.userId=crypto.randomUUID();window.dispatchEvent(new Event('focus'));});await editor.waitFor({state:'hidden'});await page.evaluate(()=>{window.qa.workspaceMode='error';});await page.getByRole('button',{name:'Actualizar',exact:true}).click();await page.getByText('QA: no se pudo leer el negocio.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Corregir',exact:true}).count(),0);});
 await check(`${viewport.name}: readonly and layout`,async()=>{await page.goto(`${origin}/?readonly=1`);await page.getByText('Tu rol permite consultar los cierres, pero no modificarlos.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Nuevo cierre',exact:true}).isDisabled(),true);await noOverflow(page);});
 }
}});
