/** Real advance review UI with inert actions, local fixtures, no provider/DB. */
import { assert, root, runUiHarness, noOverflow, viewports, clickTwice } from '../scripts/ui-fixtures/harness.mjs';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
await mkdir(join(root,'.test-artifacts'),{recursive:true});
const actions=join(root,'.test-artifacts/inbox-advances-actions.mjs');
await writeFile(actions,`export async function approveInboxAdvanceAction(input){window.qa.calls.push(structuredClone(input));if(window.qa.delay)await new Promise(resolve=>window.qa.release=resolve);if(window.qa.throwResponse)throw Error('Respuesta perdida QA');return window.qa.responses.shift()??{ok:true,persisted:true,advanceId:'00000000-0000-4000-8000-000000000020'};}`);
await runUiHarness({name:'inbox-advances',actionModules:{'@/app/actions/inbox-advances':actions},entry:`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {InboxAdvanceReviewDialog} from '${root}/app/inbox/advance-review.tsx';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');const closed=new URLSearchParams(location.search).has('closed');
const review={extractionId:id(10),businessId:id(2),userId:id(1),branchId:id(3),employees:[{id:id(4),fullName:'Juan QA',role:'Cocina',branchId:id(3),branchName:'Central QA',updatedAt:'2026-01-01T00:00:00.123456Z'},{id:id(5),fullName:'Juan QA',role:'Salón',branchId:id(3),branchName:'Central QA',updatedAt:'2026-01-01T00:00:00.654321Z'}],expectedFields:{employee_name:'Juan',amount:20},detectedName:'Juan',amount:'20',date:'',closed,targetAdvanceId:closed?id(20):null};
window.qa={calls:[],responses:[],saved:0,closed:0,delay:false,throwResponse:false};
function App(){const[open,setOpen]=useState(true);return <><button onClick={()=>setOpen(true)}>Abrir revisión</button>{open&&<InboxAdvanceReviewDialog review={review} onClose={()=>{window.qa.closed++;setOpen(false)}} onSaved={()=>{window.qa.saved++;setOpen(false)}}/>}</>};createRoot(document.getElementById('root')).render(<App/>);`,async run({page,origin,check,screenshot}){
 const employeeId='00000000-0000-4000-8000-000000000005';const key='gastropilot:inbox-advance:00000000-0000-4000-8000-000000000002:00000000-0000-4000-8000-000000000001:00000000-0000-4000-8000-000000000010:v1';
 const confirm=()=>page.getByRole('button',{name:'Confirmar adelanto',exact:true});const retry=()=>page.getByRole('button',{name:'Reintentar misma revisión',exact:true});
 async function reset(){await page.goto(origin);await page.evaluate(()=>sessionStorage.clear());await page.reload();await page.getByRole('heading',{name:'Revisar adelanto',exact:true}).waitFor();}
 async function choose(){await page.getByLabel('Empleado del adelanto').selectOption(employeeId);await page.getByLabel('Fecha del adelanto').fill('2026-01-02');await page.getByLabel('Importe del adelanto').fill('25,20');}
 for(const viewport of viewports){
  await page.setViewportSize({width:viewport.width,height:viewport.height});await reset();
  await check(`${viewport.name}: no fuzzy identity or invented date`,async()=>{await noOverflow(page);assert.equal(await page.getByLabel('Empleado del adelanto').inputValue(),'');assert.equal(await page.getByLabel('Fecha del adelanto').inputValue(),'');await confirm().click();await page.getByRole('alert').waitFor();assert.equal(await page.evaluate(()=>window.qa.calls.length),0);await screenshot(`${viewport.name}-exact-identity`);});
  await check(`${viewport.name}: cancelling unsent review creates no advance`,async()=>{await choose();await page.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await page.evaluate(()=>window.qa.calls.length),0);await page.getByRole('button',{name:'Abrir revisión',exact:true}).click();assert.equal(await page.getByLabel('Empleado del adelanto').inputValue(),'');});
  await check(`${viewport.name}: double click sends selected UUID and version once`,async()=>{await choose();await page.evaluate(()=>{window.qa.delay=true;window.qa.responses.push({ok:false,persisted:'unknown',error:'Respuesta interrumpida'});});await clickTwice(confirm());await page.waitForFunction(()=>window.qa.calls.length===1);assert.equal(await page.getByRole('button',{name:'Cancelar',exact:true}).isDisabled(),true);assert.equal(await page.getByLabel('Empleado del adelanto').isDisabled(),true);await page.evaluate(()=>window.qa.release());await retry().waitFor();const sent=await page.evaluate(()=>window.qa.calls[0]);assert.equal(sent.review.employeeId,employeeId);assert.equal(sent.review.expectedEmployeeUpdatedAt,'2026-01-01T00:00:00.654321Z');assert.equal(sent.review.amount,'25.20');assert.equal(sent.review.date,'2026-01-02');await screenshot(`${viewport.name}-uncertain`);});
  await check(`${viewport.name}: close/reopen and reload preserve exact unknown proposal`,async()=>{const first=await page.evaluate(()=>window.qa.calls[0]);await page.getByRole('button',{name:'Cerrar y revisar',exact:true}).click();await page.getByRole('button',{name:'Abrir revisión',exact:true}).click();await retry().waitFor();assert.equal(await page.getByLabel('Importe del adelanto').isDisabled(),true);await page.reload();await retry().waitFor();await retry().click();await page.waitForFunction(()=>window.qa.saved===1);assert.deepEqual(await page.evaluate(()=>window.qa.calls[0]),first);assert.equal(await page.evaluate(k=>sessionStorage.getItem(k),key),null);});
  await check(`${viewport.name}: reload after committed extraction still permits exact replay`,async()=>{await reset();await choose();await page.evaluate(()=>{window.qa.throwResponse=true;});await confirm().click();await retry().waitFor();const first=await page.evaluate(()=>window.qa.calls[0]);await page.goto(origin+'?closed=1');await retry().waitFor();await retry().click();await page.waitForFunction(()=>window.qa.saved===1);assert.deepEqual(await page.evaluate(()=>window.qa.calls[0]),first);});
  await check(`${viewport.name}: approved extraction with no journal is read only`,async()=>{await page.goto(origin+'?closed=1');await page.getByText('Esta extracción ya está aprobada.',{exact:false}).waitFor();assert.equal(await confirm().count(),0);assert.equal(await retry().count(),0);assert.equal(await page.evaluate(()=>window.qa.calls.length),0);});
  await check(`${viewport.name}: corrupt recovery fails closed`,async()=>{await reset();await page.evaluate(k=>sessionStorage.setItem(k,'broken'),key);await page.reload();await page.getByRole('alert').waitFor();assert.equal(await confirm().isDisabled(),true);assert.equal(await page.evaluate(()=>window.qa.calls.length),0);});
  await check(`${viewport.name}: storage failure prevents dispatch`,async()=>{await reset();await choose();await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('Storage denied QA')};});await confirm().click();await page.getByRole('alert').waitFor();assert.equal(await page.evaluate(()=>window.qa.calls.length),0);await page.reload();});
 }
}});
