/** Real expense review component with isolated fixture actions; no provider/DB. */
import { assert, root, runUiHarness, noOverflow, viewports, clickTwice } from '../scripts/ui-fixtures/harness.mjs';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
await mkdir(join(root,'.test-artifacts'),{recursive:true});
const actions=join(root,'.test-artifacts/inbox-expenses-actions.mjs');
await writeFile(actions,`export async function approveInboxExpenseAction(input){window.qa.calls.push(structuredClone(input));if(window.qa.delay)await new Promise(resolve=>window.qa.release=resolve);return window.qa.responses.shift()??{ok:true,persisted:true,expenseId:'00000000-0000-4000-8000-000000000020',version:1};}`);
await runUiHarness({name:'inbox-expenses',actionModules:{'@/app/actions/inbox-expenses':actions},entry:`import React from 'react';import {createRoot} from 'react-dom/client';import {InboxExpenseReviewDialog} from '${root}/app/inbox/expense-review.tsx';
 const review={extractionId:'00000000-0000-4000-8000-000000000010',businessId:'00000000-0000-4000-8000-000000000002',userId:'00000000-0000-4000-8000-000000000001',branchId:'00000000-0000-4000-8000-000000000003',branches:[{id:'00000000-0000-4000-8000-000000000003',name:'Central QA ficticia'}],expectedFields:{concept:'Internet QA',amount:20,payment_method:'Efectivo',date:'2026-10-09'},name:'Internet QA',category:'Servicios',amount:'20',dueDate:null};window.qa={calls:[],responses:[],saved:0,closed:0,delay:false};createRoot(document.getElementById('root')).render(<InboxExpenseReviewDialog review={review} onClose={()=>window.qa.closed++} onSaved={()=>window.qa.saved++}/>);`,async run({page,origin,check,screenshot}){
 for(const viewport of viewports){
  await page.setViewportSize({width:viewport.width,height:viewport.height});await page.goto(origin);await page.evaluate(()=>sessionStorage.clear());await page.reload();await page.getByRole('heading',{name:'Revisar gasto',exact:true}).waitFor();
  await check(`${viewport.name}: no inferred paid status or due date`,async()=>{await noOverflow(page);assert.equal(await page.getByLabel('Estado contable del gasto').inputValue(),'');assert.equal(await page.getByLabel('Vencimiento del gasto').inputValue(),'');await page.getByRole('button',{name:'Confirmar gasto',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.evaluate(()=>window.qa.calls.length),0);await screenshot(`${viewport.name}-review`);});
  await check(`${viewport.name}: double click sends one explicit review`,async()=>{await page.getByLabel('Estado contable del gasto').selectOption('pending');await page.evaluate(()=>{window.qa.delay=true;window.qa.responses.push({ok:false,persisted:'unknown',error:'Respuesta interrumpida'});});await clickTwice(page.getByRole('button',{name:'Confirmar gasto',exact:true}));await page.waitForFunction(()=>window.qa.calls.length===1);assert.equal(await page.getByRole('button',{name:'Cancelar',exact:true}).isDisabled(),true);await page.evaluate(()=>window.qa.release());await page.getByRole('button',{name:'Reintentar misma revisión',exact:true}).waitFor();assert.equal(await page.getByLabel('Monto del gasto').isDisabled(),true);await screenshot(`${viewport.name}-uncertain`);});
  await check(`${viewport.name}: reload recovers immutable review and stable extraction identity`,async()=>{const first=await page.evaluate(()=>window.qa.calls[0]);await page.reload();await page.getByRole('button',{name:'Reintentar misma revisión',exact:true}).waitFor();assert.equal(await page.getByLabel('Monto del gasto').isDisabled(),true);await page.getByRole('button',{name:'Reintentar misma revisión',exact:true}).click();await page.waitForFunction(()=>window.qa.saved===1);assert.deepEqual(await page.evaluate(()=>window.qa.calls[0]),first);assert.equal(first.review.status,'pending');assert.equal(first.review.dueDate,null);});
 }
}});
