import path from 'node:path';
import{assert,clickTwice,editorReady,noOverflow,releaseWrites,root,runUiHarness,viewports}from'../scripts/ui-fixtures/harness.mjs';
const fixture=path.join(root,'tests/invoice-manual-ui-fixture.mjs');
await runUiHarness({name:'invoice-manual',actionModules:{'@/app/actions/invoice-review':fixture,'@/app/actions/invoices':fixture},entry:`import React from'react';import{createRoot}from'react-dom/client';import{DatabaseInvoicesView}from'${root}/app/facturas/database-view.tsx';createRoot(document.getElementById('root')).render(<DatabaseInvoicesView/>);`,async run({page,origin,check,screenshot}){
 const fill=async(editor,number)=>{await editor.getByLabel('Número real',{exact:true}).fill(number);await editor.getByLabel('Tipo de comprobante',{exact:true}).selectOption('A');await editor.getByLabel('Fecha de factura',{exact:true}).fill('2026-01-02');await editor.getByLabel('Condición o medio de pago',{exact:true}).fill('Cuenta corriente');await editor.getByLabel('Descripción 1',{exact:true}).fill('Harina real QA ficticia');await editor.getByLabel('Cantidad 1',{exact:true}).fill('1.5');await editor.getByLabel('Unidad 1',{exact:true}).fill('kg');await editor.getByLabel('Precio unitario 1',{exact:true}).fill('2.01');await editor.getByLabel('Insumo para stock 1',{exact:true}).selectOption({label:'Harina QA ficticia · kg'});await editor.getByLabel('Impuesto total',{exact:true}).fill('0.63');};
 const review=editor=>editor.getByRole('checkbox',{name:/Revisé el comprobante/});const close=async editor=>{await editor.getByRole('button',{name:/^(Cancelar|Cerrar y revisar)$/}).click();await editor.waitFor({state:'hidden'});};const open=async()=>{await page.getByRole('button',{name:'Nueva factura manual',exact:true}).click();return editorReady(page);};
 for(const viewport of viewports){await page.setViewportSize({width:viewport.width,height:viewport.height});await page.goto(origin);await page.getByText('Comprobante sin datos confirmados',{exact:true}).waitFor();
 await check(`${viewport.name}: failed OCR is blank and approved records are immutable`,async()=>{const approved=page.locator('.card').filter({has:page.getByText('B · APPROVED-1',{exact:true})});assert.equal(await approved.getByRole('button',{name:'Revisar',exact:true}).count(),0);await page.getByRole('button',{name:'Revisar',exact:true}).click();const editor=await editorReady(page);for(const label of['Número real','Tipo de comprobante','Fecha de factura','Condición o medio de pago','Impuesto total','Descripción 1','Cantidad 1'])assert.equal(await editor.getByLabel(label,{exact:true}).inputValue(),'');assert.equal(await review(editor).isChecked(),false);await fill(editor,'REAL-QA-1');await screenshot(`${viewport.name}-failed-ocr-review`);await close(editor);assert.equal(await page.evaluate(()=>window.qa.saveCalls),0);});
 await check(`${viewport.name}: explicit checkbox resets when data changes and repeat save commits once`,async()=>{await page.getByRole('button',{name:'Revisar',exact:true}).click();const editor=await editorReady(page);await fill(editor,'REAL-QA-1');assert.equal(await editor.getByRole('button',{name:'Guardar revisión',exact:true}).isDisabled(),true);await review(editor).check();await editor.getByLabel('Número real',{exact:true}).fill('REAL-QA-2');assert.equal(await review(editor).isChecked(),false);await review(editor).check();await page.evaluate(()=>{window.qa.holdWrites=true;});await clickTwice(editor.getByRole('button',{name:'Guardar revisión',exact:true}));await page.waitForFunction(()=>window.qa.saveCalls===1);await editor.getByRole('button',{name:'Cerrar',exact:true}).click();assert.equal(await editor.isVisible(),true);await releaseWrites(page);await editor.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.qa.purchases),0);await page.getByText('A · REAL-QA-2',{exact:true}).waitFor();});
 await check(`${viewport.name}: review history preserves original then approval binds exact version`,async()=>{const card=page.locator('.card').filter({has:page.getByText('A · REAL-QA-2',{exact:true})});await card.getByRole('button',{name:'Detalle e historial',exact:true}).click();let editor=await editorReady(page);await editor.getByText('Revisiones manuales auditadas',{exact:true}).waitFor();await editor.locator('summary').filter({hasText:'Versión 1'}).click();await editor.getByText('Antes: TEMP-failed · Total 0,00',{exact:true}).waitFor();await editor.getByRole('button',{name:'Cerrar detalle',exact:true}).click();await editor.waitFor({state:'hidden'});await card.getByRole('button',{name:'Aprobar versión revisada',exact:true}).click();editor=await editorReady(page);assert.equal(await editor.getByRole('button',{name:'Confirmar aprobación',exact:true}).isDisabled(),true);await editor.getByRole('checkbox',{name:/Confirmo aprobar esta versión/}).check();await clickTwice(editor.getByRole('button',{name:'Confirmar aprobación',exact:true}));await editor.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.qa.approveCalls),1);assert.equal(await page.evaluate(()=>window.qa.purchases),1);assert.equal(await card.getByRole('button',{name:'Revisar',exact:true}).count(),0);await screenshot(`${viewport.name}-approved`);});
 await check(`${viewport.name}: uncertain review freezes and replays exact payload`,async()=>{const editor=await open();await fill(editor,'UNCERTAIN-QA');await review(editor).check();await page.evaluate(()=>{window.qa.response='throw-after-commit';});await editor.getByRole('button',{name:'Guardar revisión',exact:true}).click();await editor.getByText(/No pudimos confirmar el resultado/).waitFor();assert.equal(await editor.getByLabel('Número real',{exact:true}).isDisabled(),true);await close(editor);assert.equal(await page.getByRole('button',{name:'Nueva factura manual',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Reintentar mismo intento',exact:true}).click();await page.getByText(/Hay una operación de factura pendiente/).waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.qa.invoices.filter(inv=>inv.number==='UNCERTAIN-QA').length),1);assert.deepEqual(await page.evaluate(()=>window.qa.writes.at(-1).input),await page.evaluate(()=>window.qa.writes.at(-2).input));});
 await check(`${viewport.name}: session switch cancels draft and failed reads remove stale rows`,async()=>{const editor=await open();await fill(editor,'OLD-SESSION');await page.evaluate(()=>{window.qa.userId=crypto.randomUUID();window.dispatchEvent(new Event('focus'));});await editor.waitFor({state:'hidden'});await page.evaluate(()=>{window.qa.workspaceMode='error';});await page.getByRole('button',{name:'Actualizar',exact:true}).click();await page.getByText('QA: lectura de facturas falló.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Revisar',exact:true}).count(),0);});
 await check(`${viewport.name}: read-only role and viewport overflow`,async()=>{await page.goto(`${origin}/?readonly=1`);await page.getByText('Tu rol permite consultar facturas, pero no modificarlas.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Nueva factura manual',exact:true}).isDisabled(),true);await noOverflow(page);await screenshot(`${viewport.name}-readonly`);});
 }
}});
