import test from "node:test";
import assert from "node:assert/strict";
import Module from "node:module";
import {canSeeModule,hasPermission} from "../lib/permissions";
import * as manual from "../lib/invoices/manual";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const state={database:true,authenticated:true,active:true,role:"owner",userId:id(1),businessId:id(2),enabled:["invoices_ocr"],calls:[] as any[],paths:[] as string[],revisions:[] as string[],readError:false,cacheError:false};
const makeDb=(transport:string)=>({rpc:async(name:string,args:any)=>{state.calls.push({transport,name,args});if(name==="get_invoice_review_revision")return{data:state.revisions.shift()??"revision",error:null};return{data:{ok:true,id:id(9),version:1,purchase_id:id(10)},error:null};},from:(table:string)=>{let single=false;const q:any={select:()=>q,eq:()=>q,in:()=>q,order:()=>q,range:()=>q,maybeSingle:()=>{single=true;return q;},then:(resolve:any)=>{const rows=table==="profiles"?[{active:state.active}]:table==="invoices"?[{id:id(9),total:"3.65",tax:"0.63"}]:table==="invoice_items"?[{invoice_id:id(9),qty_numeric:"0.000001",unit_price:"2.01"}]:[];return Promise.resolve({data:single?rows[0]:rows,count:rows.length,error:state.readError?{code:"fail"}:null}).then(resolve);}};return q;}});
const loader=Module as any;const original=loader._load;loader._load=function(name:string,...args:any[]){const mocks:any={"next/cache":{revalidatePath:(path:string)=>{state.paths.push(path);if(state.cacheError)throw new Error("cache");}},"@/lib/data/auth":{getCurrentUserContext:async()=>({isAuthenticated:state.authenticated,userId:state.userId,businessId:state.businessId,role:state.role,enabledModules:state.enabled,assignedBranchIds:null})},"@/lib/supabase/server":{createSupabaseServerClient:async()=>makeDb("authenticated")},"@/lib/supabase/admin":{createSupabaseAdminClient:()=>makeDb("service_role")},"@/lib/env":{isDatabaseMode:()=>state.database},"@/lib/permissions":{hasPermission,canSeeModule},"@/lib/invoices/manual":manual};return name in mocks?mocks[name]:original.call(this,name,...args);};const actions=require("../app/actions/invoice-review") as typeof import("../app/actions/invoice-review");loader._load=original;
const input=()=>({requestId:id(8),businessId:id(2),userId:id(1),id:null,expectedVersion:null,branchId:id(3),supplierId:null,number:"REAL-12",type:"A",invoiceDate:"2026-01-01",dueDate:null,taxId:null,paymentMethod:"Pending",tax:"0.63",items:[{description:"Line",quantity:"1.5",unit:"kg",unitPrice:"2.01",ingredientId:null}],reviewed:true});
function reset(){Object.assign(state,{database:true,authenticated:true,active:true,role:"owner",userId:id(1),businessId:id(2),enabled:["invoices_ocr"],calls:[],paths:[],revisions:[],readError:false,cacheError:false});}
test("review saves with authenticated identity and approval uses exactly one version-bound service call",async()=>{reset();assert.equal((await actions.saveInvoiceReviewAction(input())).ok,true);assert.equal(state.calls.length,1);assert.equal(state.calls[0].transport,"authenticated");assert.equal(state.calls[0].name,"save_invoice_review_atomic");reset();const approval={requestId:id(8),businessId:id(2),userId:id(1),id:id(9),expectedVersion:3};assert.equal((await actions.approveReviewedInvoiceAction(approval)).ok,true);assert.deepEqual(state.calls[0],{transport:"service_role",name:"approve_invoice_reviewed_atomic",args:{p_business_id:id(2),p_actor_id:id(1),p_input:approval}});});
test("manual invoice actions deny invalid session profile module role and changed business before mutation",async()=>{for(const change of[()=>{state.database=false;},()=>{state.authenticated=false;},()=>{state.active=false;},()=>{state.role="viewer";},()=>{state.role="accountant";},()=>{state.enabled=[];},()=>{state.userId=id(20);},()=>{state.businessId=id(20); }]){reset();change();assert.equal((await actions.saveInvoiceReviewAction(input())).ok,false);assert.equal(state.calls.length,0);}reset();state.role="manager";assert.equal((await actions.saveInvoiceReviewAction(input())).ok,true);state.calls=[];assert.equal((await actions.approveReviewedInvoiceAction({requestId:id(8),businessId:id(2),userId:id(1),id:id(9),expectedVersion:1})).ok,false);assert.equal(state.calls.length,0);});
test("invoice reads are complete consistent and precision-preserving, cache failure does not reverse confirmed writes",async()=>{reset();const result=await actions.getInvoiceWorkspaceAction();assert.equal(result.ok,true);if(result.ok)assert.equal(result.data.invoices[0].items[0].qty_numeric,"0.000001");reset();state.revisions=["old","new"];assert.equal((await actions.getInvoiceWorkspaceAction()).ok,false);reset();state.readError=true;assert.equal((await actions.getInvoiceWorkspaceAction()).ok,false);reset();state.cacheError=true;assert.equal((await actions.saveInvoiceReviewAction(input())).ok,true);});
