export const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export type InvoiceLineInput = { description: string; quantity: string; unit: string; unitPrice: string; ingredientId: string | null };
export type InvoiceSaveInput = { requestId: string; businessId: string; userId: string; id: string | null; expectedVersion: number | null; branchId: string; supplierId: string | null; number: string; type: "A" | "B" | "C"; invoiceDate: string; dueDate: string | null; taxId: string | null; paymentMethod: string; tax: string; items: InvoiceLineInput[]; reviewed: true };
export type InvoiceApproveInput = { requestId: string; businessId: string; userId: string; id: string; expectedVersion: number };
export type InvoiceOperation = { kind: "save"; input: InvoiceSaveInput } | { kind: "approve"; input: InvoiceApproveInput };
export type InvoiceMutationResult = { ok: true; persisted: true; id: string; version: number; purchaseId?: string } | { ok: false; persisted: false | "unknown"; error: string };
export type InvoiceItem = { id: string; description: string; qty_numeric: string | null; unit: string; unit_price: string; total: string; matched_ingredient_id: string | null; suggested_ingredient_id: string | null; match_status: string };
export type ManualInvoice = { id: string; business_id: string; branch_id: string | null; supplier_id: string | null; number: string; type: string; invoice_date: string; due_date: string | null; tax_id: string | null; payment_method: string; subtotal: string; tax: string; total: string; status: string; source: string; ocr_text: string | null; processing_error: string | null; edit_version: number; reviewed_version: number | null; reviewed_at: string | null; reviewed_by: string | null; storage_path: string | null; items: InvoiceItem[] };
export type InvoiceWorkspace = { businessId: string; userId: string; branches: { id: string; name: string }[]; suppliers: { id: string; name: string }[]; ingredients: { id: string; name: string; unit: string }[]; invoices: ManualInvoice[]; canEdit: boolean; canApprove: boolean };
export type InvoiceHistory = { request_id: string; actor_role: string; created_at: string; before_snapshot: { invoice: ManualInvoice; items: InvoiceItem[] } | null; after_snapshot: { invoice: ManualInvoice; items: InvoiceItem[] }; result: { version: number } };
const money = /^(0|[1-9]\d{0,9})(\.\d{1,2})?$/;
const qty = /^(0|[1-9]\d{0,11})(\.\d{1,6})?$/;
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Datos de factura inválidos."); return value as Record<string, unknown>; }
function exact(p: Record<string, unknown>, keys: string[]) { if (Object.keys(p).length !== keys.length || Object.keys(p).some(k => !keys.includes(k))) throw new Error("La factura contiene datos no admitidos."); }
function uuid(v: unknown): string { if (typeof v !== "string" || !UUID.test(v)) throw new Error("Identificador inválido."); return v; }
function text(v: unknown, max: number): string { if (typeof v !== "string" || !v.trim() || v.length > max || /[\x00-\x1f\x7f]/.test(v)) throw new Error("Completá los campos obligatorios con datos válidos."); return v.trim(); }
function date(v: unknown): string { if (typeof v !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(v) || v < "1900-01-01" || Number.isNaN(Date.parse(`${v}T12:00:00Z`)) || new Date(`${v}T12:00:00Z`).toISOString().slice(0,10) !== v) throw new Error("Revisá las fechas de la factura."); return v; }
function decimal(v: unknown, pattern: RegExp): string { if (typeof v !== "string" || !pattern.test(v)) throw new Error("Revisá las cantidades y los importes, sin separadores de miles."); return v; }
function scaled(value: string, places: number): bigint { const [whole, fraction = ""] = value.split("."); return BigInt(whole) * 10n ** BigInt(places) + BigInt(fraction.padEnd(places,"0")); }
function cents(value: bigint): string { return `${value / 100n}.${String(value % 100n).padStart(2,"0")}`; }
export function invoiceTotals(items: InvoiceLineInput[], tax: string): { subtotal: string; tax: string; total: string; lines: string[] } {
 const lines = items.map(item => { decimal(item.quantity,qty); decimal(item.unitPrice,money); const quantity=scaled(item.quantity,6); if (quantity<=0n) throw new Error("Las cantidades deben ser mayores que cero."); const total=(quantity*scaled(item.unitPrice,2)+500000n)/1000000n; if(total>=1000000000000n)throw new Error("Un importe excede el máximo admitido."); return total; });
 decimal(tax,money);const subtotal=lines.reduce((a,b)=>a+b,0n);const total=subtotal+scaled(tax,2);if(total>=1000000000000n)throw new Error("El total excede el máximo admitido.");return{subtotal:cents(subtotal),tax,total:cents(total),lines:lines.map(cents)};
}
export function parseInvoiceOperation(kind: "save" | "approve", input: unknown): InvoiceOperation {
 const p=object(input); exact(p,kind==="save"?["requestId","businessId","userId","id","expectedVersion","branchId","supplierId","number","type","invoiceDate","dueDate","taxId","paymentMethod","tax","items","reviewed"]:["requestId","businessId","userId","id","expectedVersion"]);
 const base={requestId:uuid(p.requestId),businessId:uuid(p.businessId),userId:uuid(p.userId),id:p.id===null?null:uuid(p.id),expectedVersion:p.expectedVersion as number|null};
 if(base.id===null?base.expectedVersion!==null:!Number.isSafeInteger(base.expectedVersion)||Number(base.expectedVersion)<0)throw new Error("La versión cambió. Volvé a abrir la factura.");
 if(kind==="approve"){if(!base.id||base.expectedVersion===null)throw new Error("Elegí una versión revisada para aprobar.");return{kind,input:{...base,id:base.id,expectedVersion:base.expectedVersion}};}
 if(p.reviewed!==true)throw new Error("Confirmá que revisaste los datos y cada línea de la factura.");
 const number=text(p.number,120);if(/^TEMP-/i.test(number))throw new Error("Ingresá el número real del comprobante.");
 if(!["A","B","C"].includes(p.type as string))throw new Error("Elegí el tipo de comprobante.");
 if(!Array.isArray(p.items)||p.items.length<1||p.items.length>100)throw new Error("Ingresá entre 1 y 100 líneas revisadas.");
 const items=p.items.map(raw=>{const item=object(raw);exact(item,["description","quantity","unit","unitPrice","ingredientId"]);return{description:text(item.description,500),quantity:decimal(item.quantity,qty),unit:text(item.unit,20),unitPrice:decimal(item.unitPrice,money),ingredientId:item.ingredientId===null?null:uuid(item.ingredientId)};});
 const tax=decimal(p.tax,money);invoiceTotals(items,tax);const invoiceDate=date(p.invoiceDate);const dueDate=p.dueDate===null?null:date(p.dueDate);if(dueDate&&dueDate<invoiceDate)throw new Error("El vencimiento debe ser igual o posterior a la fecha.");
 return{kind,input:{...base,branchId:uuid(p.branchId),supplierId:p.supplierId===null?null:uuid(p.supplierId),number,type:p.type as "A"|"B"|"C",invoiceDate,dueDate,taxId:p.taxId===null?null:text(p.taxId,32),paymentMethod:text(p.paymentMethod,100),tax,items,reviewed:true}};
}
export function invoiceDraft(row: ManualInvoice | null): Omit<InvoiceSaveInput,"requestId"|"businessId"|"userId"|"reviewed"> & { reviewed: boolean } {
 const unsafe=!!row&&["uploaded","processing","failed"].includes(row.status)&&row.reviewed_version===null;
 return{id:row?.id??null,expectedVersion:row?.edit_version??null,branchId:row?.branch_id??"",supplierId:unsafe?null:row?.supplier_id??null,number:unsafe||row?.number.startsWith("TEMP-")?"":row?.number??"",type:unsafe?"" as "A":row?.type as "A"??"" as "A",invoiceDate:unsafe?"":row?.invoice_date??"",dueDate:unsafe?null:row?.due_date??null,taxId:unsafe?null:row?.tax_id??null,paymentMethod:unsafe?"":row?.payment_method??"",tax:unsafe?"":row?.tax??"",items:unsafe||!row?.items.length?[{description:"",quantity:"",unit:"",unitPrice:"",ingredientId:null}]:row.items.map(item=>({description:item.description,quantity:item.qty_numeric??"",unit:item.unit,unitPrice:item.unit_price,ingredientId:item.matched_ingredient_id})),reviewed:false};
}
export const invoiceJournalKey=(businessId:string,userId:string)=>`gp:invoice-review:v1:${businessId}:${userId}`;
export function readInvoiceOperation(raw:string|null,businessId:string,userId:string):InvoiceOperation|null{if(raw===null)return null;const p=object(JSON.parse(raw));exact(p,["kind","input"]);if(p.kind!=="save"&&p.kind!=="approve")throw new Error("Operación inválida.");const result=parseInvoiceOperation(p.kind,p.input);if(result.input.businessId!==businessId||result.input.userId!==userId)throw new Error("La referencia pertenece a otra sesión.");return result;}
const ERRORS:Record<string,string>={invoice_permission_denied:"No tenés permiso para esta operación.",invoice_module_disabled:"El módulo Facturas está deshabilitado.",invoice_context_changed:"Cambió la sesión o el negocio. Recargá para continuar.",invoice_conflict:"La factura cambió. Cerrá el editor y revisá la versión actual.",invoice_readonly:"Las facturas aprobadas no se pueden modificar.",invoice_processing:"El OCR sigue procesando. Esperá a que termine o quede marcado como fallido.",invoice_review_required:"Guardá una revisión explícita de esta versión antes de aprobar.",invoice_branch_forbidden:"La sucursal no está disponible.",invoice_supplier_forbidden:"El proveedor no pertenece al negocio o está inactivo.",invoice_ingredient_forbidden:"Un insumo no pertenece al negocio.",invoice_invalid_units:"La unidad de una línea no es compatible con el insumo elegido.",invoice_idempotency_conflict:"La referencia ya se utilizó con otros datos. Conservá el intento para revisarlo.",invoice_invalid_input:"Revisá todos los campos y líneas del comprobante.",invoice_invalid_date:"La fecha es inválida o está en el futuro.",invoice_not_found:"La factura no está disponible en este negocio."};
export async function invoiceRpc(db:{rpc:(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:unknown}>},operation:InvoiceOperation):Promise<InvoiceMutationResult>{
 try{const response=await db.rpc(operation.kind==="save"?"save_invoice_review_atomic":"approve_invoice_reviewed_atomic",{p_business_id:operation.input.businessId,...(operation.kind==="approve"?{p_actor_id:operation.input.userId}:{}),p_input:operation.input});const data=response.data as {ok?:boolean;id?:string;version?:number;purchase_id?:string;error?:string}|null;
 if(!response.error&&data?.ok===true&&typeof data.id==="string"&&UUID.test(data.id)&&Number.isSafeInteger(data.version)&&data.version!>=0&&(operation.kind!=="approve"||typeof data.purchase_id==="string"&&UUID.test(data.purchase_id)))return{ok:true,persisted:true,id:data.id,version:data.version!,...(data.purchase_id?{purchaseId:data.purchase_id}:{})};
 if(!response.error&&data?.ok===false)return{ok:false,persisted:false,error:ERRORS[data.error??""]??"La factura no se guardó. Revisá los datos, insumos y permisos."};
 }catch{/* A response may be lost after commit. */}return{ok:false,persisted:"unknown",error:"No pudimos confirmar el resultado. Reintentá exactamente esta operación para evitar duplicados."};
}
