-- AI recommendations and financial balance snapshots are generated by trusted
-- backend processes. Authenticated users may read them through RLS, but direct
-- Data API writes must not bypass the application permission boundary.

drop policy if exists "ai_recommendations rw" on public.ai_recommendations;
create policy "ai_recommendations read"
on public.ai_recommendations
for select
to authenticated
using (public.is_member_of_business(business_id));

drop policy if exists "balance_snapshots rw" on public.balance_snapshots;
create policy "balance_snapshots read"
on public.balance_snapshots
for select
to authenticated
using (public.is_member_of_business(business_id));

revoke insert, update, delete, truncate, references, trigger on public.ai_recommendations from anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on public.balance_snapshots from anon, authenticated;

grant select on public.ai_recommendations to authenticated;
grant select on public.balance_snapshots to authenticated;
